; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S < %s -p loop-vectorize -force-vector-width=4 -enable-early-exit-vectorization-with-side-effects -force-target-supports-masked-memory-ops | FileCheck %s

define void @side_effect(ptr dereferenceable(128) %p, ptr noalias %q) {
; CHECK-LABEL: define void @side_effect(
; CHECK-SAME: ptr dereferenceable(128) [[P:%.*]], ptr noalias [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br label %[[LATCH:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP]] ], [ [[INDEX_NEXT:%.*]], %[[EXIT:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD]], zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP1]], i1 false)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[TMP2]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = icmp ult <4 x i64> <i64 0, i64 1, i64 2, i64 3>, [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr i8, ptr [[Q]], i32 [[IV]]
; CHECK-NEXT:    [[WIDE_LOAD1:%.*]] = call <4 x i8> @llvm.masked.load.v4i8.p0(ptr align 1 [[GEP2]], <4 x i1> [[TMP7]], <4 x i8> poison)
; CHECK-NEXT:    [[TMP3:%.*]] = add <4 x i8> [[WIDE_LOAD1]], splat (i8 1)
; CHECK-NEXT:    call void @llvm.masked.store.v4i8.p0(<4 x i8> [[TMP3]], ptr align 1 [[GEP2]], <4 x i1> [[TMP7]])
; CHECK-NEXT:    [[TMP4:%.*]] = freeze <4 x i1> [[TMP1]]
; CHECK-NEXT:    [[TMP5:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP4]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[IV]], 4
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i32 [[INDEX_NEXT]], 128
; CHECK-NEXT:    br i1 [[TMP5]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[LATCH]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT1:.*]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    br label %[[EXIT1]]
; CHECK:       [[EXIT1]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep1 = getelementptr i8, ptr %p, i32 %iv
  %ld1 = load i8, ptr %gep1
  %earlyexit = icmp eq i8 %ld1, 0
  br i1 %earlyexit, label %exit, label %latch

latch:
  %gep2 = getelementptr i8, ptr %q, i32 %iv
  %ld2 = load i8, ptr %gep2
  %add = add i8 %ld2, 1
  store i8 %add, ptr %gep2

  %iv.next = add i32 %iv, 1
  %exitcond = icmp ne i32 %iv.next, 128
  br i1 %exitcond, label %loop, label %exit

exit:
  ret void
}

define void @side_effect_chained_exits(ptr dereferenceable(128) %p, ptr dereferenceable(128) %r, ptr noalias %q) {
; CHECK-LABEL: define void @side_effect_chained_exits(
; CHECK-SAME: ptr dereferenceable(128) [[P:%.*]], ptr dereferenceable(128) [[R:%.*]], ptr noalias [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br label %[[LATCH:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP]] ], [ [[INDEX_NEXT:%.*]], %[[LATCH1:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD]], zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP1]], i1 false)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <4 x i64> poison, i64 [[TMP2]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT1:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT1]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ult <4 x i64> <i64 0, i64 1, i64 2, i64 3>, [[BROADCAST_SPLAT1]]
; CHECK-NEXT:    [[GEP3:%.*]] = getelementptr i8, ptr [[R]], i32 [[IV]]
; CHECK-NEXT:    [[WIDE_LOAD1:%.*]] = call <4 x i8> @llvm.masked.load.v4i8.p0(ptr align 1 [[GEP3]], <4 x i1> [[TMP10]], <4 x i8> poison)
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD1]], zeroinitializer
; CHECK-NEXT:    [[TMP14:%.*]] = select <4 x i1> [[TMP10]], <4 x i1> [[TMP3]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP14]], i1 false)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[TMP4]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP5:%.*]] = icmp ult <4 x i64> <i64 0, i64 1, i64 2, i64 3>, [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP13:%.*]] = select <4 x i1> [[TMP10]], <4 x i1> [[TMP5]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[Q]], i32 [[IV]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <4 x i8> @llvm.masked.load.v4i8.p0(ptr align 1 [[TMP6]], <4 x i1> [[TMP13]], <4 x i8> poison)
; CHECK-NEXT:    [[TMP7:%.*]] = add <4 x i8> [[WIDE_MASKED_LOAD]], splat (i8 1)
; CHECK-NEXT:    call void @llvm.masked.store.v4i8.p0(<4 x i8> [[TMP7]], ptr align 1 [[TMP6]], <4 x i1> [[TMP13]])
; CHECK-NEXT:    [[TMP8:%.*]] = select <4 x i1> [[TMP1]], <4 x i1> splat (i1 true), <4 x i1> [[TMP3]]
; CHECK-NEXT:    [[TMP9:%.*]] = freeze <4 x i1> [[TMP8]]
; CHECK-NEXT:    [[EARLYEXIT3:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP9]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[IV]], 4
; CHECK-NEXT:    [[TMP11:%.*]] = icmp eq i32 [[INDEX_NEXT]], 128
; CHECK-NEXT:    br i1 [[EARLYEXIT3]], label %[[EXIT:.*]], label %[[LATCH1]]
; CHECK:       [[LATCH1]]:
; CHECK-NEXT:    br i1 [[TMP11]], label %[[MIDDLE_BLOCK:.*]], label %[[LATCH]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT1:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP9]], i1 false)
; CHECK-NEXT:    [[TMP12:%.*]] = extractelement <4 x i1> [[TMP1]], i64 [[FIRST_ACTIVE_LANE]]
; CHECK-NEXT:    br i1 [[TMP12]], label %[[VECTOR_EARLY_EXIT_0:.*]], label %[[VECTOR_EARLY_EXIT_1:.*]]
; CHECK:       [[VECTOR_EARLY_EXIT_1]]:
; CHECK-NEXT:    br label %[[EXIT1]]
; CHECK:       [[VECTOR_EARLY_EXIT_0]]:
; CHECK-NEXT:    br label %[[EXIT1]]
; CHECK:       [[EXIT1]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep1 = getelementptr i8, ptr %p, i32 %iv
  %ld1 = load i8, ptr %gep1
  %earlyexit1 = icmp eq i8 %ld1, 0
  br i1 %earlyexit1, label %exit, label %check2

check2:
  %gep2 = getelementptr i8, ptr %r, i32 %iv
  %ld2 = load i8, ptr %gep2
  %earlyexit2 = icmp eq i8 %ld2, 0
  br i1 %earlyexit2, label %exit, label %latch

latch:
  %gep3 = getelementptr i8, ptr %q, i32 %iv
  %ld3 = load i8, ptr %gep3
  %add = add i8 %ld3, 1
  store i8 %add, ptr %gep3
  %iv.next = add i32 %iv, 1
  %exitcond = icmp ne i32 %iv.next, 128
  br i1 %exitcond, label %loop, label %exit

exit:
  ret void
}

; Two early exits in opposite arms of a diamond, so they form no dominance
; chain and neither one dominates the store in the latch. Both condition loads
; sit in the header, but a cut taken in one arm still cannot mask the store for
; lanes travelling down the other.
define void @side_effect_diamond_exits(ptr dereferenceable(128) %p, ptr dereferenceable(128) %r, ptr dereferenceable(128) %s, ptr noalias %q) {
; CHECK-LABEL: define void @side_effect_diamond_exits(
; CHECK-SAME: ptr dereferenceable(128) [[P:%.*]], ptr dereferenceable(128) [[R:%.*]], ptr dereferenceable(128) [[S:%.*]], ptr noalias [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr i8, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    [[LD1:%.*]] = load i8, ptr [[GEP1]], align 1
; CHECK-NEXT:    [[COND:%.*]] = icmp slt i8 [[LD1]], 0
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr i8, ptr [[R]], i32 [[IV]]
; CHECK-NEXT:    [[LD2:%.*]] = load i8, ptr [[GEP2]], align 1
; CHECK-NEXT:    [[GEP3:%.*]] = getelementptr i8, ptr [[S]], i32 [[IV]]
; CHECK-NEXT:    [[LD3:%.*]] = load i8, ptr [[GEP3]], align 1
; CHECK-NEXT:    br i1 [[COND]], label %[[LEFT:.*]], label %[[RIGHT:.*]]
; CHECK:       [[LEFT]]:
; CHECK-NEXT:    [[EARLYEXIT1:%.*]] = icmp eq i8 [[LD2]], 0
; CHECK-NEXT:    br i1 [[EARLYEXIT1]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[RIGHT]]:
; CHECK-NEXT:    [[EARLYEXIT2:%.*]] = icmp eq i8 [[LD3]], 1
; CHECK-NEXT:    br i1 [[EARLYEXIT2]], label %[[EXIT]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[GEP4:%.*]] = getelementptr i8, ptr [[Q]], i32 [[IV]]
; CHECK-NEXT:    [[LD4:%.*]] = load i8, ptr [[GEP4]], align 1
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[LD4]], 1
; CHECK-NEXT:    store i8 [[ADD]], ptr [[GEP4]], align 1
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i32 [[IV_NEXT]], 128
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep1 = getelementptr i8, ptr %p, i32 %iv
  %ld1 = load i8, ptr %gep1
  %cond = icmp slt i8 %ld1, 0
  %gep2 = getelementptr i8, ptr %r, i32 %iv
  %ld2 = load i8, ptr %gep2
  %gep3 = getelementptr i8, ptr %s, i32 %iv
  %ld3 = load i8, ptr %gep3
  br i1 %cond, label %left, label %right

left:
  %earlyexit1 = icmp eq i8 %ld2, 0
  br i1 %earlyexit1, label %exit, label %latch

right:
  %earlyexit2 = icmp eq i8 %ld3, 1
  br i1 %earlyexit2, label %exit, label %latch

latch:
  %gep4 = getelementptr i8, ptr %q, i32 %iv
  %ld4 = load i8, ptr %gep4
  %add = add i8 %ld4, 1
  store i8 %add, ptr %gep4
  %iv.next = add i32 %iv, 1
  %exitcond = icmp ne i32 %iv.next, 128
  br i1 %exitcond, label %loop, label %exit

exit:
  ret void
}

; The early exit sits in a predicated block, so its condition load only runs
; on the iterations where %pred holds.
define void @side_effect_predicated_exit(ptr dereferenceable(128) %p, ptr noalias %q) {
; CHECK-LABEL: define void @side_effect_predicated_exit(
; CHECK-SAME: ptr dereferenceable(128) [[P:%.*]], ptr noalias [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr i8, ptr [[Q]], i32 [[IV]]
; CHECK-NEXT:    [[LD1:%.*]] = load i8, ptr [[GEP1]], align 1
; CHECK-NEXT:    [[PRED:%.*]] = icmp sgt i8 [[LD1]], 0
; CHECK-NEXT:    br i1 [[PRED]], label %[[GUARDED:.*]], label %[[LATCH]]
; CHECK:       [[GUARDED]]:
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr i8, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    [[LD2:%.*]] = load i8, ptr [[GEP2]], align 1
; CHECK-NEXT:    [[EARLYEXIT:%.*]] = icmp eq i8 [[LD2]], 0
; CHECK-NEXT:    br i1 [[EARLYEXIT]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[LD1]], 1
; CHECK-NEXT:    store i8 [[ADD]], ptr [[GEP1]], align 1
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i32 [[IV_NEXT]], 128
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep1 = getelementptr i8, ptr %q, i32 %iv
  %ld1 = load i8, ptr %gep1
  %pred = icmp sgt i8 %ld1, 0
  br i1 %pred, label %guarded, label %latch

guarded:
  %gep2 = getelementptr i8, ptr %p, i32 %iv
  %ld2 = load i8, ptr %gep2
  %earlyexit = icmp eq i8 %ld2, 0
  br i1 %earlyexit, label %exit, label %latch

latch:
  %add = add i8 %ld1, 1
  store i8 %add, ptr %gep1
  %iv.next = add i32 %iv, 1
  %exitcond = icmp ne i32 %iv.next, 128
  br i1 %exitcond, label %loop, label %exit

exit:
  ret void
}

; A plain dereferenceable load sitting between the two exits. It doesn't force
; the scalar-tail style, but it is still masked: its block lies in the shadow
; of the first exit's cut branch.
define void @side_effect_deref_load_between_exits(ptr dereferenceable(128) %p, ptr dereferenceable(128) %r, ptr dereferenceable(128) %s, ptr noalias %q) {
; CHECK-LABEL: define void @side_effect_deref_load_between_exits(
; CHECK-SAME: ptr dereferenceable(128) [[P:%.*]], ptr dereferenceable(128) [[R:%.*]], ptr dereferenceable(128) [[S:%.*]], ptr noalias [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[P]], i32 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD]], zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP1]], i1 false)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[TMP2]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ult <4 x i64> <i64 0, i64 1, i64 2, i64 3>, [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[R]], i32 [[INDEX]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <4 x i8> @llvm.masked.load.v4i8.p0(ptr align 1 [[TMP4]], <4 x i1> [[TMP3]], <4 x i8> poison)
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[S]], i32 [[INDEX]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD1:%.*]] = call <4 x i8> @llvm.masked.load.v4i8.p0(ptr align 1 [[TMP5]], <4 x i1> [[TMP3]], <4 x i8> poison)
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq <4 x i8> [[WIDE_MASKED_LOAD1]], zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = select <4 x i1> [[TMP3]], <4 x i1> [[TMP6]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP8:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP7]], i1 false)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT2:%.*]] = insertelement <4 x i64> poison, i64 [[TMP8]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT3:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT2]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP9:%.*]] = icmp ult <4 x i64> <i64 0, i64 1, i64 2, i64 3>, [[BROADCAST_SPLAT3]]
; CHECK-NEXT:    [[TMP10:%.*]] = select <4 x i1> [[TMP3]], <4 x i1> [[TMP9]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[Q]], i32 [[INDEX]]
; CHECK-NEXT:    call void @llvm.masked.store.v4i8.p0(<4 x i8> [[WIDE_MASKED_LOAD]], ptr align 1 [[TMP11]], <4 x i1> [[TMP10]])
; CHECK-NEXT:    [[TMP12:%.*]] = select <4 x i1> [[TMP1]], <4 x i1> splat (i1 true), <4 x i1> [[TMP6]]
; CHECK-NEXT:    [[TMP13:%.*]] = freeze <4 x i1> [[TMP12]]
; CHECK-NEXT:    [[TMP14:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP13]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[INDEX]], 4
; CHECK-NEXT:    [[TMP15:%.*]] = icmp eq i32 [[INDEX_NEXT]], 128
; CHECK-NEXT:    br i1 [[TMP14]], label %[[VECTOR_EARLY_EXIT_CHECK:.*]], label %[[VECTOR_BODY_INTERIM]]
; CHECK:       [[VECTOR_BODY_INTERIM]]:
; CHECK-NEXT:    br i1 [[TMP15]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[VECTOR_EARLY_EXIT_CHECK]]:
; CHECK-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP13]], i1 false)
; CHECK-NEXT:    [[TMP16:%.*]] = extractelement <4 x i1> [[TMP1]], i64 [[FIRST_ACTIVE_LANE]]
; CHECK-NEXT:    br i1 [[TMP16]], label %[[VECTOR_EARLY_EXIT_0:.*]], label %[[VECTOR_EARLY_EXIT_1:.*]]
; CHECK:       [[VECTOR_EARLY_EXIT_1]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[VECTOR_EARLY_EXIT_0]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep1 = getelementptr i8, ptr %p, i32 %iv
  %ld1 = load i8, ptr %gep1
  %ee1 = icmp eq i8 %ld1, 0
  br i1 %ee1, label %exit, label %mid

mid:
  %gep2 = getelementptr i8, ptr %r, i32 %iv
  %ld2 = load i8, ptr %gep2
  %gep3 = getelementptr i8, ptr %s, i32 %iv
  %ld3 = load i8, ptr %gep3
  %ee2 = icmp eq i8 %ld3, 0
  br i1 %ee2, label %exit, label %latch

latch:
  %gep4 = getelementptr i8, ptr %q, i32 %iv
  store i8 %ld2, ptr %gep4
  %iv.next = add i32 %iv, 1
  %ec = icmp ne i32 %iv.next, 128
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

; Chained exits leaving to different blocks, so the cut masks coexist with the
; dispatch chain that picks the exit and extracts the live-out at the exiting
; lane.
define i32 @side_effect_chained_exits_distinct_exit_blocks(ptr dereferenceable(128) %p, ptr dereferenceable(128) %r, ptr noalias %q) {
; CHECK-LABEL: define i32 @side_effect_chained_exits_distinct_exit_blocks(
; CHECK-SAME: ptr dereferenceable(128) [[P:%.*]], ptr dereferenceable(128) [[R:%.*]], ptr noalias [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[P]], i32 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD]], zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP1]], i1 false)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[TMP2]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ult <4 x i64> <i64 0, i64 1, i64 2, i64 3>, [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[R]], i32 [[INDEX]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <4 x i8> @llvm.masked.load.v4i8.p0(ptr align 1 [[TMP4]], <4 x i1> [[TMP3]], <4 x i8> poison)
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq <4 x i8> [[WIDE_MASKED_LOAD]], zeroinitializer
; CHECK-NEXT:    [[TMP6:%.*]] = select <4 x i1> [[TMP3]], <4 x i1> [[TMP5]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP6]], i1 false)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT3:%.*]] = insertelement <4 x i64> poison, i64 [[TMP7]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT4:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT3]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP8:%.*]] = icmp ult <4 x i64> <i64 0, i64 1, i64 2, i64 3>, [[BROADCAST_SPLAT4]]
; CHECK-NEXT:    [[TMP9:%.*]] = select <4 x i1> [[TMP3]], <4 x i1> [[TMP8]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[Q]], i32 [[INDEX]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD5:%.*]] = call <4 x i8> @llvm.masked.load.v4i8.p0(ptr align 1 [[TMP10]], <4 x i1> [[TMP9]], <4 x i8> poison)
; CHECK-NEXT:    [[TMP11:%.*]] = add <4 x i8> [[WIDE_MASKED_LOAD5]], splat (i8 1)
; CHECK-NEXT:    call void @llvm.masked.store.v4i8.p0(<4 x i8> [[TMP11]], ptr align 1 [[TMP10]], <4 x i1> [[TMP9]])
; CHECK-NEXT:    [[TMP12:%.*]] = select <4 x i1> [[TMP1]], <4 x i1> splat (i1 true), <4 x i1> [[TMP5]]
; CHECK-NEXT:    [[TMP13:%.*]] = freeze <4 x i1> [[TMP12]]
; CHECK-NEXT:    [[TMP14:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP13]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[INDEX]], 4
; CHECK-NEXT:    [[TMP15:%.*]] = icmp eq i32 [[INDEX_NEXT]], 128
; CHECK-NEXT:    br i1 [[TMP14]], label %[[VECTOR_EARLY_EXIT_CHECK:.*]], label %[[VECTOR_BODY_INTERIM]]
; CHECK:       [[VECTOR_BODY_INTERIM]]:
; CHECK-NEXT:    br i1 [[TMP15]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT_C:.*]]
; CHECK:       [[VECTOR_EARLY_EXIT_CHECK]]:
; CHECK-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP13]], i1 false)
; CHECK-NEXT:    [[TMP16:%.*]] = extractelement <4 x i1> [[TMP1]], i64 [[FIRST_ACTIVE_LANE]]
; CHECK-NEXT:    br i1 [[TMP16]], label %[[VECTOR_EARLY_EXIT_0:.*]], label %[[VECTOR_EARLY_EXIT_1:.*]]
; CHECK:       [[VECTOR_EARLY_EXIT_1]]:
; CHECK-NEXT:    br label %[[EXIT_B:.*]]
; CHECK:       [[VECTOR_EARLY_EXIT_0]]:
; CHECK-NEXT:    [[TMP17:%.*]] = trunc i64 [[FIRST_ACTIVE_LANE]] to i32
; CHECK-NEXT:    [[TMP18:%.*]] = add i32 [[INDEX]], [[TMP17]]
; CHECK-NEXT:    br label %[[EXIT_A:.*]]
; CHECK:       [[EXIT_A]]:
; CHECK-NEXT:    ret i32 [[TMP18]]
; CHECK:       [[EXIT_B]]:
; CHECK-NEXT:    ret i32 -1
; CHECK:       [[EXIT_C]]:
; CHECK-NEXT:    ret i32 -2
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep1 = getelementptr i8, ptr %p, i32 %iv
  %ld1 = load i8, ptr %gep1
  %ee1 = icmp eq i8 %ld1, 0
  br i1 %ee1, label %exit.a, label %mid

mid:
  %gep2 = getelementptr i8, ptr %r, i32 %iv
  %ld2 = load i8, ptr %gep2
  %ee2 = icmp eq i8 %ld2, 0
  br i1 %ee2, label %exit.b, label %latch

latch:
  %gep3 = getelementptr i8, ptr %q, i32 %iv
  %ld3 = load i8, ptr %gep3
  %add = add i8 %ld3, 1
  store i8 %add, ptr %gep3
  %iv.next = add i32 %iv, 1
  %ec = icmp ne i32 %iv.next, 128
  br i1 %ec, label %loop, label %exit.c

exit.a:
  ret i32 %iv

exit.b:
  ret i32 -1

exit.c:
  ret i32 -2
}

; The store may alias the load feeding the exit condition, which looks like it
; should sink the loop. A runtime alias check makes it legal instead.
define void @side_effect_may_alias_condition_load(ptr dereferenceable(128) %p, ptr %q) {
; CHECK-LABEL: define void @side_effect_may_alias_condition_load(
; CHECK-SAME: ptr dereferenceable(128) [[P:%.*]], ptr [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_MEMCHECK:.*]]
; CHECK:       [[VECTOR_MEMCHECK]]:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr nuw i8, ptr [[P]], i64 128
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[Q]], [[SCEVGEP]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[P]], inttoptr (i64 -1 to ptr)
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[P]], i32 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1, !alias.scope [[META6:![0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD]], zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP1]], i1 false)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[TMP2]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = icmp ult <4 x i64> <i64 0, i64 1, i64 2, i64 3>, [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[Q]], i32 [[INDEX]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <4 x i8> @llvm.masked.load.v4i8.p0(ptr align 1 [[TMP4]], <4 x i1> [[TMP3]], <4 x i8> poison), !alias.scope [[META9:![0-9]+]], !noalias [[META6]]
; CHECK-NEXT:    [[TMP5:%.*]] = add <4 x i8> [[WIDE_MASKED_LOAD]], splat (i8 1)
; CHECK-NEXT:    call void @llvm.masked.store.v4i8.p0(<4 x i8> [[TMP5]], ptr align 1 [[TMP4]], <4 x i1> [[TMP3]]), !alias.scope [[META9]], !noalias [[META6]]
; CHECK-NEXT:    [[TMP6:%.*]] = freeze <4 x i1> [[TMP1]]
; CHECK-NEXT:    [[TMP7:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP6]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[INDEX]], 4
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[INDEX_NEXT]], 128
; CHECK-NEXT:    br i1 [[TMP7]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[VECTOR_BODY_INTERIM]]
; CHECK:       [[VECTOR_BODY_INTERIM]]:
; CHECK-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP11:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr i8, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    [[LD1:%.*]] = load i8, ptr [[GEP1]], align 1
; CHECK-NEXT:    [[EE1:%.*]] = icmp eq i8 [[LD1]], 0
; CHECK-NEXT:    br i1 [[EE1]], label %[[EXIT]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr i8, ptr [[Q]], i32 [[IV]]
; CHECK-NEXT:    [[LD2:%.*]] = load i8, ptr [[GEP2]], align 1
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[LD2]], 1
; CHECK-NEXT:    store i8 [[ADD]], ptr [[GEP2]], align 1
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ne i32 [[IV_NEXT]], 128
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep1 = getelementptr i8, ptr %p, i32 %iv
  %ld1 = load i8, ptr %gep1
  %ee1 = icmp eq i8 %ld1, 0
  br i1 %ee1, label %exit, label %latch

latch:
  %gep2 = getelementptr i8, ptr %q, i32 %iv
  %ld2 = load i8, ptr %gep2
  %add = add i8 %ld2, 1
  store i8 %add, ptr %gep2
  %iv.next = add i32 %iv, 1
  %ec = icmp ne i32 %iv.next, 128
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

; The store precedes the exit test, so no cut can mask it: the exiting lane has
; already stored by the time its condition is known. Handled by masking to the
; lanes before the exiting one and letting the scalar loop redo that iteration.
define void @side_effect_store_before_exit(ptr dereferenceable(128) %p, ptr noalias %q) {
; CHECK-LABEL: define void @side_effect_store_before_exit(
; CHECK-SAME: ptr dereferenceable(128) [[P:%.*]], ptr noalias [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[P]], i32 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD]], zeroinitializer
; CHECK-NEXT:    [[TMP6:%.*]] = freeze <4 x i1> [[TMP1]]
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP6]], i1 false)
; CHECK-NEXT:    [[TMP3:%.*]] = trunc i64 [[TMP2]] to i32
; CHECK-NEXT:    [[UNCOUNTABLE_EXIT_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i32(i32 0, i32 [[TMP3]])
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[Q]], i32 [[INDEX]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <4 x i8> @llvm.masked.load.v4i8.p0(ptr align 1 [[TMP4]], <4 x i1> [[UNCOUNTABLE_EXIT_MASK]], <4 x i8> poison)
; CHECK-NEXT:    [[TMP5:%.*]] = add <4 x i8> [[WIDE_MASKED_LOAD]], splat (i8 1)
; CHECK-NEXT:    call void @llvm.masked.store.v4i8.p0(<4 x i8> [[TMP5]], ptr align 1 [[TMP4]], <4 x i1> [[UNCOUNTABLE_EXIT_MASK]])
; CHECK-NEXT:    [[TMP7:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP6]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[INDEX]], 4
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[INDEX_NEXT]], 128
; CHECK-NEXT:    [[TMP9:%.*]] = or i1 [[TMP7]], [[TMP8]]
; CHECK-NEXT:    br i1 [[TMP9]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP13:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[TMP10:%.*]] = add i32 [[INDEX]], [[TMP3]]
; CHECK-NEXT:    [[TMP11:%.*]] = icmp eq i32 [[TMP10]], 128
; CHECK-NEXT:    br i1 [[TMP11]], label %[[EXIT:.*]], label %[[SCALAR_PH:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[TMP10]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr i8, ptr [[Q]], i32 [[IV]]
; CHECK-NEXT:    [[LD2:%.*]] = load i8, ptr [[GEP2]], align 1
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[LD2]], 1
; CHECK-NEXT:    store i8 [[ADD]], ptr [[GEP2]], align 1
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr i8, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    [[LD1:%.*]] = load i8, ptr [[GEP1]], align 1
; CHECK-NEXT:    [[EE1:%.*]] = icmp eq i8 [[LD1]], 0
; CHECK-NEXT:    br i1 [[EE1]], label %[[EXIT]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ne i32 [[IV_NEXT]], 128
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT]], !llvm.loop [[LOOP14:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep2 = getelementptr i8, ptr %q, i32 %iv
  %ld2 = load i8, ptr %gep2
  %add = add i8 %ld2, 1
  store i8 %add, ptr %gep2
  %gep1 = getelementptr i8, ptr %p, i32 %iv
  %ld1 = load i8, ptr %gep1
  %ee1 = icmp eq i8 %ld1, 0
  br i1 %ee1, label %exit, label %latch

latch:
  %iv.next = add i32 %iv, 1
  %ec = icmp ne i32 %iv.next, 128
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

; A chain of early exits inside a predicated region, with the store in its own
; block under the same predicate rather than in the latch. Both exits dominate
; the store, so this is vectorized.
define void @side_effect_predicated_chained_exits(ptr dereferenceable(128) %p, ptr dereferenceable(128) %r, ptr noalias dereferenceable(128) %q) {
; CHECK-LABEL: define void @side_effect_predicated_chained_exits(
; CHECK-SAME: ptr dereferenceable(128) [[P:%.*]], ptr dereferenceable(128) [[R:%.*]], ptr noalias dereferenceable(128) [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br label %[[GUARDED1:.*]]
; CHECK:       [[GUARDED1]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[LOOP]] ], [ [[INDEX_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[Q]], i32 [[IV]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[TMP0]], align 1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp sgt <4 x i8> [[WIDE_LOAD]], zeroinitializer
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr i8, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <4 x i8> @llvm.masked.load.v4i8.p0(ptr align 1 [[GEP1]], <4 x i1> [[TMP1]], <4 x i8> poison)
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq <4 x i8> [[WIDE_MASKED_LOAD]], zeroinitializer
; CHECK-NEXT:    [[TMP7:%.*]] = select <4 x i1> [[TMP1]], <4 x i1> [[TMP3]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP7]], i1 false)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[TMP4]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP5:%.*]] = icmp ult <4 x i64> <i64 0, i64 1, i64 2, i64 3>, [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP6:%.*]] = select <4 x i1> [[TMP1]], <4 x i1> [[TMP5]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr i8, ptr [[R]], i32 [[IV]]
; CHECK-NEXT:    [[WIDE_MASKED_LOAD1:%.*]] = call <4 x i8> @llvm.masked.load.v4i8.p0(ptr align 1 [[GEP2]], <4 x i1> [[TMP6]], <4 x i8> poison)
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq <4 x i8> [[WIDE_MASKED_LOAD1]], zeroinitializer
; CHECK-NEXT:    [[TMP9:%.*]] = select <4 x i1> [[TMP6]], <4 x i1> [[TMP8]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP10:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP9]], i1 false)
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT2:%.*]] = insertelement <4 x i64> poison, i64 [[TMP10]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT3:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT2]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP11:%.*]] = icmp ult <4 x i64> <i64 0, i64 1, i64 2, i64 3>, [[BROADCAST_SPLAT3]]
; CHECK-NEXT:    [[TMP13:%.*]] = select <4 x i1> [[TMP6]], <4 x i1> [[TMP11]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP14:%.*]] = add <4 x i8> [[WIDE_LOAD]], splat (i8 1)
; CHECK-NEXT:    call void @llvm.masked.store.v4i8.p0(<4 x i8> [[TMP14]], ptr align 1 [[TMP0]], <4 x i1> [[TMP13]])
; CHECK-NEXT:    [[PREDPHI:%.*]] = select <4 x i1> [[TMP1]], <4 x i1> [[TMP3]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[PREDPHI4:%.*]] = select <4 x i1> [[TMP1]], <4 x i1> [[TMP8]], <4 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP15:%.*]] = select <4 x i1> [[PREDPHI]], <4 x i1> splat (i1 true), <4 x i1> [[PREDPHI4]]
; CHECK-NEXT:    [[TMP16:%.*]] = freeze <4 x i1> [[TMP15]]
; CHECK-NEXT:    [[EE2:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP16]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[IV]], 4
; CHECK-NEXT:    [[TMP18:%.*]] = icmp eq i32 [[INDEX_NEXT]], 128
; CHECK-NEXT:    br i1 [[EE2]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    br i1 [[TMP18]], label %[[MIDDLE_BLOCK:.*]], label %[[GUARDED1]], !llvm.loop [[LOOP15:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT1:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP16]], i1 false)
; CHECK-NEXT:    [[TMP19:%.*]] = extractelement <4 x i1> [[PREDPHI]], i64 [[FIRST_ACTIVE_LANE]]
; CHECK-NEXT:    br i1 [[TMP19]], label %[[VECTOR_EARLY_EXIT_0:.*]], label %[[VECTOR_EARLY_EXIT_1:.*]]
; CHECK:       [[VECTOR_EARLY_EXIT_1]]:
; CHECK-NEXT:    br label %[[EXIT1]]
; CHECK:       [[VECTOR_EARLY_EXIT_0]]:
; CHECK-NEXT:    br label %[[EXIT1]]
; CHECK:       [[EXIT1]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep0 = getelementptr i8, ptr %q, i32 %iv
  %ld0 = load i8, ptr %gep0
  %pred = icmp sgt i8 %ld0, 0
  br i1 %pred, label %guarded1, label %latch

guarded1:
  %gep1 = getelementptr i8, ptr %p, i32 %iv
  %ld1 = load i8, ptr %gep1
  %ee1 = icmp eq i8 %ld1, 0
  br i1 %ee1, label %exit, label %guarded2

guarded2:
  %gep2 = getelementptr i8, ptr %r, i32 %iv
  %ld2 = load i8, ptr %gep2
  %ee2 = icmp eq i8 %ld2, 0
  br i1 %ee2, label %exit, label %store.bb

store.bb:
  %add = add i8 %ld0, 1
  store i8 %add, ptr %gep0
  br label %latch

latch:
  %iv.next = add i32 %iv, 1
  %ec = icmp ne i32 %iv.next, 128
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

; A chain of exits, but the store sits in the second exiting block itself, so
; that exit cannot dominate it and its cut comes too late.
define void @side_effect_store_between_exits(ptr dereferenceable(128) %p, ptr dereferenceable(128) %r, ptr noalias %q) {
; CHECK-LABEL: define void @side_effect_store_between_exits(
; CHECK-SAME: ptr dereferenceable(128) [[P:%.*]], ptr dereferenceable(128) [[R:%.*]], ptr noalias [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr i8, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    [[LD1:%.*]] = load i8, ptr [[GEP1]], align 1
; CHECK-NEXT:    [[EE1:%.*]] = icmp eq i8 [[LD1]], 0
; CHECK-NEXT:    br i1 [[EE1]], label %[[EXIT:.*]], label %[[MID:.*]]
; CHECK:       [[MID]]:
; CHECK-NEXT:    [[GEP3:%.*]] = getelementptr i8, ptr [[Q]], i32 [[IV]]
; CHECK-NEXT:    [[LD3:%.*]] = load i8, ptr [[GEP3]], align 1
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[LD3]], 1
; CHECK-NEXT:    store i8 [[ADD]], ptr [[GEP3]], align 1
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr i8, ptr [[R]], i32 [[IV]]
; CHECK-NEXT:    [[LD2:%.*]] = load i8, ptr [[GEP2]], align 1
; CHECK-NEXT:    [[EE2:%.*]] = icmp eq i8 [[LD2]], 0
; CHECK-NEXT:    br i1 [[EE2]], label %[[EXIT]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ne i32 [[IV_NEXT]], 128
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep1 = getelementptr i8, ptr %p, i32 %iv
  %ld1 = load i8, ptr %gep1
  %ee1 = icmp eq i8 %ld1, 0
  br i1 %ee1, label %exit, label %mid

mid:
  %gep3 = getelementptr i8, ptr %q, i32 %iv
  %ld3 = load i8, ptr %gep3
  %add = add i8 %ld3, 1
  store i8 %add, ptr %gep3
  %gep2 = getelementptr i8, ptr %r, i32 %iv
  %ld2 = load i8, ptr %gep2
  %ee2 = icmp eq i8 %ld2, 0
  br i1 %ee2, label %exit, label %latch

latch:
  %iv.next = add i32 %iv, 1
  %ec = icmp ne i32 %iv.next, 128
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

; The exits chain and the store is below both, but the second exit's condition
; load isn't dereferenceable, so its own block needs masking and no cut placed
; at that exit can cover it.
define void @side_effect_second_exit_load_not_dereferenceable(ptr dereferenceable(128) %p, ptr %r, ptr noalias %q) {
; CHECK-LABEL: define void @side_effect_second_exit_load_not_dereferenceable(
; CHECK-SAME: ptr dereferenceable(128) [[P:%.*]], ptr [[R:%.*]], ptr noalias [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr i8, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    [[LD1:%.*]] = load i8, ptr [[GEP1]], align 1
; CHECK-NEXT:    [[EE1:%.*]] = icmp eq i8 [[LD1]], 0
; CHECK-NEXT:    br i1 [[EE1]], label %[[EXIT:.*]], label %[[MID:.*]]
; CHECK:       [[MID]]:
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr i8, ptr [[R]], i32 [[IV]]
; CHECK-NEXT:    [[LD2:%.*]] = load i8, ptr [[GEP2]], align 1
; CHECK-NEXT:    [[EE2:%.*]] = icmp eq i8 [[LD2]], 0
; CHECK-NEXT:    br i1 [[EE2]], label %[[EXIT]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[GEP3:%.*]] = getelementptr i8, ptr [[Q]], i32 [[IV]]
; CHECK-NEXT:    [[LD3:%.*]] = load i8, ptr [[GEP3]], align 1
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[LD3]], 1
; CHECK-NEXT:    store i8 [[ADD]], ptr [[GEP3]], align 1
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ne i32 [[IV_NEXT]], 128
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep1 = getelementptr i8, ptr %p, i32 %iv
  %ld1 = load i8, ptr %gep1
  %ee1 = icmp eq i8 %ld1, 0
  br i1 %ee1, label %exit, label %mid

mid:
  %gep2 = getelementptr i8, ptr %r, i32 %iv
  %ld2 = load i8, ptr %gep2
  %ee2 = icmp eq i8 %ld2, 0
  br i1 %ee2, label %exit, label %latch

latch:
  %gep3 = getelementptr i8, ptr %q, i32 %iv
  %ld3 = load i8, ptr %gep3
  %add = add i8 %ld3, 1
  store i8 %add, ptr %gep3
  %iv.next = add i32 %iv, 1
  %ec = icmp ne i32 %iv.next, 128
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

; Three exits where the middle one sits in a diamond arm. The first and last
; exits dominate the store, but the middle one doesn't, so the exits are not
; totally ordered and the chained cut masks don't apply.
define void @side_effect_middle_exit_in_diamond(ptr dereferenceable(128) %p, ptr dereferenceable(128) %r, ptr dereferenceable(128) %s, ptr noalias %q) {
; CHECK-LABEL: define void @side_effect_middle_exit_in_diamond(
; CHECK-SAME: ptr dereferenceable(128) [[P:%.*]], ptr dereferenceable(128) [[R:%.*]], ptr dereferenceable(128) [[S:%.*]], ptr noalias [[Q:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr i8, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    [[LD1:%.*]] = load i8, ptr [[GEP1]], align 1
; CHECK-NEXT:    [[EE1:%.*]] = icmp eq i8 [[LD1]], 0
; CHECK-NEXT:    br i1 [[EE1]], label %[[EXIT:.*]], label %[[MID:.*]]
; CHECK:       [[MID]]:
; CHECK-NEXT:    [[COND:%.*]] = icmp ult i32 [[IV]], 64
; CHECK-NEXT:    br i1 [[COND]], label %[[LEFT:.*]], label %[[MERGE:.*]]
; CHECK:       [[LEFT]]:
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr i8, ptr [[R]], i32 [[IV]]
; CHECK-NEXT:    [[LD2:%.*]] = load i8, ptr [[GEP2]], align 1
; CHECK-NEXT:    [[EE2:%.*]] = icmp eq i8 [[LD2]], 0
; CHECK-NEXT:    br i1 [[EE2]], label %[[EXIT]], label %[[MERGE]]
; CHECK:       [[MERGE]]:
; CHECK-NEXT:    [[GEP3:%.*]] = getelementptr i8, ptr [[S]], i32 [[IV]]
; CHECK-NEXT:    [[LD3:%.*]] = load i8, ptr [[GEP3]], align 1
; CHECK-NEXT:    [[EE3:%.*]] = icmp eq i8 [[LD3]], 0
; CHECK-NEXT:    br i1 [[EE3]], label %[[EXIT]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[GEP4:%.*]] = getelementptr i8, ptr [[Q]], i32 [[IV]]
; CHECK-NEXT:    [[LD4:%.*]] = load i8, ptr [[GEP4]], align 1
; CHECK-NEXT:    [[ADD:%.*]] = add i8 [[LD4]], 1
; CHECK-NEXT:    store i8 [[ADD]], ptr [[GEP4]], align 1
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp ne i32 [[IV_NEXT]], 128
; CHECK-NEXT:    br i1 [[EC]], label %[[LOOP]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %latch ]
  %gep1 = getelementptr i8, ptr %p, i32 %iv
  %ld1 = load i8, ptr %gep1
  %ee1 = icmp eq i8 %ld1, 0
  br i1 %ee1, label %exit, label %mid

mid:
  %cond = icmp ult i32 %iv, 64
  br i1 %cond, label %left, label %merge

left:
  %gep2 = getelementptr i8, ptr %r, i32 %iv
  %ld2 = load i8, ptr %gep2
  %ee2 = icmp eq i8 %ld2, 0
  br i1 %ee2, label %exit, label %merge

merge:
  %gep3 = getelementptr i8, ptr %s, i32 %iv
  %ld3 = load i8, ptr %gep3
  %ee3 = icmp eq i8 %ld3, 0
  br i1 %ee3, label %exit, label %latch

latch:
  %gep4 = getelementptr i8, ptr %q, i32 %iv
  %ld4 = load i8, ptr %gep4
  %add = add i8 %ld4, 1
  store i8 %add, ptr %gep4
  %iv.next = add i32 %iv, 1
  %ec = icmp ne i32 %iv.next, 128
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]], [[META2]]}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META1]], [[META2]]}
; CHECK: [[META6]] = !{[[META7:![0-9]+]]}
; CHECK: [[META7]] = distinct !{[[META7]], [[META8:![0-9]+]]}
; CHECK: [[META8]] = distinct !{[[META8]], !"LVerDomain"}
; CHECK: [[META9]] = !{[[META10:![0-9]+]]}
; CHECK: [[META10]] = distinct !{[[META10]], [[META8]]}
; CHECK: [[LOOP11]] = distinct !{[[LOOP11]], [[META1]], [[META2]]}
; CHECK: [[LOOP12]] = distinct !{[[LOOP12]], [[META1]]}
; CHECK: [[LOOP13]] = distinct !{[[LOOP13]], [[META1]], [[META2]]}
; CHECK: [[LOOP14]] = distinct !{[[LOOP14]], [[META2]], [[META1]]}
; CHECK: [[LOOP15]] = distinct !{[[LOOP15]], [[META1]], [[META2]]}
;.
