name: Copilot Setup Steps

on:
  workflow_dispatch:
  push:
    paths:
      - .github-copilot-steps.yml
  pull_request:
    paths:
      - .github-copilot-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-4-core
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
