; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -mtriple=riscv64 -disable-output -passes="print<cost-model>" 2>&1 | FileCheck %s
define i32 @f(i1 %c) {
; CHECK-LABEL: 'f'
; CHECK-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: br i1 %c, label %a, label %b
; CHECK-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: br label %d
; CHECK-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: br label %d
; CHECK-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %x = phi i32 [ 42, %a ], [ 123456, %b ]
; CHECK-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret i32 %x
;
  br i1 %c, label %a, label %b
a:
  br label %d
b:
  br label %d
d:
  %x = phi i32 [42, %a], [123456, %b]
  ret i32 %x
}
