; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt -disable-output < %s -p loop-vectorize -vplan-print-after=introduceMasksAndLinearize -vplan-print-vector-region-scope 2>&1 | FileCheck %s

; Test various CFGs generated by early exits

;     vector.body
;        /   \
;       /     \
;   exiting1   \
;     / \       \
;    /   \       |
;   /   join1    |
;  /    /    \   |
; / exiting2  \  |
; \    |    \  \ |
;  \   |     join2
;   \  |    /
;    \ |   /
;     latch
define void @multi_early_exit_predicated_nested(ptr %p1, ptr %p2, i1 %c1, i1 %c2, i1 %ee1, i1 %ee2, i32 %n) {
; CHECK-LABEL: VPlan for loop in 'multi_early_exit_predicated_nested'
; CHECK-NEXT:  <x1> vector loop: {
; CHECK-NEXT:  vp<[[VP3:%[0-9]+]]> = CANONICAL-IV
; CHECK-EMPTY:
; CHECK-NEXT:    vector.body:
; CHECK-NEXT:      ir<%iv> = WIDEN-INDUCTION ir<0>, ir<1>, vp<[[VP0:%[0-9]+]]>
; CHECK-NEXT:    Successor(s): exiting1
; CHECK-EMPTY:
; CHECK-NEXT:    exiting1:
; CHECK-NEXT:    Successor(s): join1
; CHECK-EMPTY:
; CHECK-NEXT:    join1:
; CHECK-NEXT:      EMIT vp<[[VP4:%[0-9]+]]> = not ir<%ee1>
; CHECK-NEXT:      EMIT vp<[[VP5:%[0-9]+]]> = logical-and ir<%c1>, vp<[[VP4]]>
; CHECK-NEXT:    Successor(s): exiting2
; CHECK-EMPTY:
; CHECK-NEXT:    exiting2:
; CHECK-NEXT:      EMIT vp<[[VP6:%[0-9]+]]> = logical-and vp<[[VP5]]>, ir<%c2>
; CHECK-NEXT:    Successor(s): join2
; CHECK-EMPTY:
; CHECK-NEXT:    join2:
; CHECK-NEXT:      EMIT vp<[[VP7:%[0-9]+]]> = not ir<%ee2>
; CHECK-NEXT:      EMIT vp<[[VP8:%[0-9]+]]> = logical-and vp<[[VP6]]>, vp<[[VP7]]>
; CHECK-NEXT:      EMIT vp<[[VP9:%[0-9]+]]> = not ir<%c2>
; CHECK-NEXT:      EMIT vp<[[VP10:%[0-9]+]]> = logical-and vp<[[VP5]]>, vp<[[VP9]]>
; CHECK-NEXT:      EMIT vp<[[VP11:%[0-9]+]]> = or vp<[[VP8]]>, vp<[[VP10]]>
; CHECK-NEXT:      EMIT vp<[[VP12:%[0-9]+]]> = not ir<%c1>
; CHECK-NEXT:      EMIT vp<[[VP13:%[0-9]+]]> = or vp<[[VP11]]>, vp<[[VP12]]>
; CHECK-NEXT:      EMIT vp<[[VP14:%[0-9]+]]> = or vp<[[VP8]]>, vp<[[VP10]]>
; CHECK-NEXT:      BLEND ir<%phi1.join2> = ir<1>/vp<[[VP14]]> ir<0>/vp<[[VP12]]>
; CHECK-NEXT:      EMIT vp<[[VP15:%[0-9]+]]> = or vp<[[VP10]]>, vp<[[VP12]]>
; CHECK-NEXT:      BLEND ir<%phi2.join2> = ir<1>/vp<[[VP8]]> ir<0>/vp<[[VP15]]>
; CHECK-NEXT:    Successor(s): latch
; CHECK-EMPTY:
; CHECK-NEXT:    latch:
; CHECK-NEXT:      BLEND ir<%phi1> = ir<1>/ir<%c1> ir<0>/vp<[[VP13]]>
; CHECK-NEXT:      BLEND ir<%phi2> = ir<1>/vp<[[VP6]]> ir<0>/vp<[[VP13]]>
; CHECK-NEXT:      EMIT ir<%gep1> = getelementptr ir<%p1>, ir<%iv>
; CHECK-NEXT:      EMIT store ir<%phi1>, ir<%gep1>
; CHECK-NEXT:      EMIT ir<%gep2> = getelementptr ir<%p2>, ir<%iv>
; CHECK-NEXT:      EMIT store ir<%phi2>, ir<%gep2>
; CHECK-NEXT:      EMIT ir<%iv.next> = add ir<%iv>, ir<1>
; CHECK-NEXT:      EMIT ir<%ec> = icmp eq ir<%iv.next>, ir<%n>
; CHECK-NEXT:      EMIT vp<%index.next> = add nuw vp<[[VP3]]>, vp<[[VP1:%[0-9]+]]>
; CHECK-NEXT:      EMIT branch-on-count vp<%index.next>, vp<[[VP2:%[0-9]+]]>
; CHECK-NEXT:    No successors
; CHECK-NEXT:  }
; CHECK-NEXT:  Successor(s): middle.block
;
entry:
  br label %loop

loop:
  %iv = phi i32 [0, %entry], [%iv.next, %latch]
  br i1 %c1, label %exiting1, label %join2

exiting1:
  br i1 %ee1, label %latch, label %join1

join1:
  br i1 %c2, label %exiting2, label %join2

exiting2:
  br i1 %ee2, label %latch, label %join2

join2:
  %phi1.join2 = phi i32 [1, %exiting2], [1, %join1], [0, %loop]
  %phi2.join2 = phi i32 [1, %exiting2], [0, %join1], [0, %loop]
  br label %latch

latch:
  %phi1 = phi i32 [1, %exiting1], [1, %exiting2], [%phi1.join2, %join2]
  %phi2 = phi i32 [poison, %exiting1], [1, %exiting2], [%phi2.join2, %join2]
  %gep1 = getelementptr i32, ptr %p1, i32 %iv
  store i32 %phi1, ptr %gep1
  %gep2 = getelementptr i32, ptr %p2, i32 %iv
  store i32 %phi2, ptr %gep2
  %iv.next = add i32 %iv, 1
  %ec = icmp eq i32 %iv.next, %n
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

;     vector.body
;        /   \
;       /     \
;   exiting1  /
;     / \    /
;    /   \  /
;   /   join1
;  /    /    \
; / exiting2  \
; \    |    \  \
;  \   |     join2
;   \  |    /
;    \ |   /
;     latch
define void @multi_early_exit_predicated_not_nested(ptr %p1, ptr %p2, i1 %c1, i1 %c2, i1 %ee1, i1 %ee2, i32 %n) {
; CHECK-LABEL: VPlan for loop in 'multi_early_exit_predicated_not_nested'
; CHECK-NEXT:  <x1> vector loop: {
; CHECK-NEXT:  vp<[[VP3:%[0-9]+]]> = CANONICAL-IV
; CHECK-EMPTY:
; CHECK-NEXT:    vector.body:
; CHECK-NEXT:      ir<%iv> = WIDEN-INDUCTION ir<0>, ir<1>, vp<[[VP0:%[0-9]+]]>
; CHECK-NEXT:    Successor(s): exiting1
; CHECK-EMPTY:
; CHECK-NEXT:    exiting1:
; CHECK-NEXT:    Successor(s): join1
; CHECK-EMPTY:
; CHECK-NEXT:    join1:
; CHECK-NEXT:      EMIT vp<[[VP4:%[0-9]+]]> = not ir<%ee1>
; CHECK-NEXT:      EMIT vp<[[VP5:%[0-9]+]]> = logical-and ir<%c1>, vp<[[VP4]]>
; CHECK-NEXT:      EMIT vp<[[VP6:%[0-9]+]]> = not ir<%c1>
; CHECK-NEXT:      EMIT vp<[[VP7:%[0-9]+]]> = or vp<[[VP5]]>, vp<[[VP6]]>
; CHECK-NEXT:      BLEND ir<%phi.join1> = ir<1>/vp<[[VP5]]> ir<0>/vp<[[VP6]]>
; CHECK-NEXT:    Successor(s): exiting2
; CHECK-EMPTY:
; CHECK-NEXT:    exiting2:
; CHECK-NEXT:      EMIT vp<[[VP8:%[0-9]+]]> = logical-and vp<[[VP7]]>, ir<%c2>
; CHECK-NEXT:    Successor(s): join2
; CHECK-EMPTY:
; CHECK-NEXT:    join2:
; CHECK-NEXT:      EMIT vp<[[VP9:%[0-9]+]]> = not ir<%ee2>
; CHECK-NEXT:      EMIT vp<[[VP10:%[0-9]+]]> = logical-and vp<[[VP8]]>, vp<[[VP9]]>
; CHECK-NEXT:      EMIT vp<[[VP11:%[0-9]+]]> = not ir<%c2>
; CHECK-NEXT:      EMIT vp<[[VP12:%[0-9]+]]> = logical-and vp<[[VP7]]>, vp<[[VP11]]>
; CHECK-NEXT:      EMIT vp<[[VP13:%[0-9]+]]> = or vp<[[VP10]]>, vp<[[VP12]]>
; CHECK-NEXT:      BLEND ir<%phi.join2> = ir<1>/vp<[[VP10]]> ir<0>/vp<[[VP12]]>
; CHECK-NEXT:    Successor(s): latch
; CHECK-EMPTY:
; CHECK-NEXT:    latch:
; CHECK-NEXT:      BLEND ir<%phi1> = ir<1>/ir<%c1> ir<0>/vp<[[VP7]]>
; CHECK-NEXT:      BLEND ir<%phi2> = ir<1>/vp<[[VP8]]> ir<0>/vp<[[VP13]]>
; CHECK-NEXT:      EMIT ir<%gep1> = getelementptr ir<%p1>, ir<%iv>
; CHECK-NEXT:      EMIT store ir<%phi1>, ir<%gep1>
; CHECK-NEXT:      EMIT ir<%gep2> = getelementptr ir<%p2>, ir<%iv>
; CHECK-NEXT:      EMIT store ir<%phi2>, ir<%gep2>
; CHECK-NEXT:      EMIT ir<%iv.next> = add ir<%iv>, ir<1>
; CHECK-NEXT:      EMIT ir<%ec> = icmp eq ir<%iv.next>, ir<%n>
; CHECK-NEXT:      EMIT vp<%index.next> = add nuw vp<[[VP3]]>, vp<[[VP1:%[0-9]+]]>
; CHECK-NEXT:      EMIT branch-on-count vp<%index.next>, vp<[[VP2:%[0-9]+]]>
; CHECK-NEXT:    No successors
; CHECK-NEXT:  }
; CHECK-NEXT:  Successor(s): middle.block
;
entry:
  br label %loop

loop:
  %iv = phi i32 [0, %entry], [%iv.next, %latch]
  br i1 %c1, label %exiting1, label %join1

exiting1:
  br i1 %ee1, label %latch, label %join1

join1:
  %phi.join1 = phi i32 [1, %exiting1], [0, %loop]
  br i1 %c2, label %exiting2, label %join2

exiting2:
  br i1 %ee2, label %latch, label %join2

join2:
  %phi.join2 = phi i32 [1, %exiting2], [0, %join1]
  br label %latch

latch:
  %phi1 = phi i32 [1, %exiting1], [%phi.join1, %exiting2], [%phi.join1, %join2]
  %phi2 = phi i32 [poison, %exiting1], [1, %exiting2], [%phi.join2, %join2]
  %gep1 = getelementptr i32, ptr %p1, i32 %iv
  store i32 %phi1, ptr %gep1
  %gep2 = getelementptr i32, ptr %p2, i32 %iv
  store i32 %phi2, ptr %gep2
  %iv.next = add i32 %iv, 1
  %ec = icmp eq i32 %iv.next, %n
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}

;     vector.body
;        /    \
;       /      \
;   exiting1  exiting2
;     / \      /    \
;    /   \    /      \
;   /    join1        \
;  /    /    \         \
; / exiting3 exiting4  /
; \   \  \   /  /     /
;  \   \ join2 /     /
;   \   \  |  /     /
;    +---latch-----+
define void @four_exits_2x2_diamond(ptr %p1, ptr %p2, ptr %p3, ptr %p4, i1 %c1, i1 %c2, i1 %ee1, i1 %ee2, i1 %ee3, i1 %ee4, i32 %n) {
; CHECK-LABEL: VPlan for loop in 'four_exits_2x2_diamond'
; CHECK-NEXT:  <x1> vector loop: {
; CHECK-NEXT:  vp<[[VP3:%[0-9]+]]> = CANONICAL-IV
; CHECK-EMPTY:
; CHECK-NEXT:    vector.body:
; CHECK-NEXT:      ir<%iv> = WIDEN-INDUCTION ir<0>, ir<1>, vp<[[VP0:%[0-9]+]]>
; CHECK-NEXT:    Successor(s): exiting2
; CHECK-EMPTY:
; CHECK-NEXT:    exiting2:
; CHECK-NEXT:      EMIT vp<[[VP4:%[0-9]+]]> = not ir<%c1>
; CHECK-NEXT:    Successor(s): exiting1
; CHECK-EMPTY:
; CHECK-NEXT:    exiting1:
; CHECK-NEXT:    Successor(s): join1
; CHECK-EMPTY:
; CHECK-NEXT:    join1:
; CHECK-NEXT:      EMIT vp<[[VP5:%[0-9]+]]> = not ir<%ee2>
; CHECK-NEXT:      EMIT vp<[[VP6:%[0-9]+]]> = logical-and vp<[[VP4]]>, vp<[[VP5]]>
; CHECK-NEXT:      EMIT vp<[[VP7:%[0-9]+]]> = not ir<%ee1>
; CHECK-NEXT:      EMIT vp<[[VP8:%[0-9]+]]> = logical-and ir<%c1>, vp<[[VP7]]>
; CHECK-NEXT:      EMIT vp<[[VP9:%[0-9]+]]> = or vp<[[VP6]]>, vp<[[VP8]]>
; CHECK-NEXT:      BLEND ir<%phi1.join1> = ir<0>/vp<[[VP6]]> ir<1>/vp<[[VP8]]>
; CHECK-NEXT:      BLEND ir<%phi2.join1> = ir<1>/vp<[[VP6]]> ir<0>/vp<[[VP8]]>
; CHECK-NEXT:    Successor(s): exiting4
; CHECK-EMPTY:
; CHECK-NEXT:    exiting4:
; CHECK-NEXT:      EMIT vp<[[VP10:%[0-9]+]]> = not ir<%c2>
; CHECK-NEXT:      EMIT vp<[[VP11:%[0-9]+]]> = logical-and vp<[[VP9]]>, vp<[[VP10]]>
; CHECK-NEXT:    Successor(s): exiting3
; CHECK-EMPTY:
; CHECK-NEXT:    exiting3:
; CHECK-NEXT:      EMIT vp<[[VP12:%[0-9]+]]> = logical-and vp<[[VP9]]>, ir<%c2>
; CHECK-NEXT:    Successor(s): join2
; CHECK-EMPTY:
; CHECK-NEXT:    join2:
; CHECK-NEXT:      EMIT vp<[[VP13:%[0-9]+]]> = not ir<%ee4>
; CHECK-NEXT:      EMIT vp<[[VP14:%[0-9]+]]> = logical-and vp<[[VP11]]>, vp<[[VP13]]>
; CHECK-NEXT:      EMIT vp<[[VP15:%[0-9]+]]> = not ir<%ee3>
; CHECK-NEXT:      EMIT vp<[[VP16:%[0-9]+]]> = logical-and vp<[[VP12]]>, vp<[[VP15]]>
; CHECK-NEXT:      EMIT vp<[[VP17:%[0-9]+]]> = or vp<[[VP14]]>, vp<[[VP16]]>
; CHECK-NEXT:      BLEND ir<%phi3.join2> = ir<0>/vp<[[VP14]]> ir<1>/vp<[[VP16]]>
; CHECK-NEXT:      BLEND ir<%phi4.join2> = ir<1>/vp<[[VP14]]> ir<0>/vp<[[VP16]]>
; CHECK-NEXT:    Successor(s): latch
; CHECK-EMPTY:
; CHECK-NEXT:    latch:
; CHECK-NEXT:      BLEND ir<%phi1> = ir<0>/vp<[[VP4]]> ir<1>/ir<%c1>
; CHECK-NEXT:      BLEND ir<%phi2> = ir<1>/vp<[[VP4]]> ir<0>/ir<%c1>
; CHECK-NEXT:      BLEND ir<%phi3> = ir<0>/vp<[[VP11]]> ir<1>/vp<[[VP12]]>
; CHECK-NEXT:      BLEND ir<%phi4> = ir<1>/vp<[[VP11]]> ir<0>/vp<[[VP12]]>
; CHECK-NEXT:      EMIT ir<%gep1> = getelementptr ir<%p1>, ir<%iv>
; CHECK-NEXT:      EMIT store ir<%phi1>, ir<%gep1>
; CHECK-NEXT:      EMIT ir<%gep2> = getelementptr ir<%p2>, ir<%iv>
; CHECK-NEXT:      EMIT store ir<%phi2>, ir<%gep2>
; CHECK-NEXT:      EMIT ir<%gep3> = getelementptr ir<%p3>, ir<%iv>
; CHECK-NEXT:      EMIT store ir<%phi3>, ir<%gep3>
; CHECK-NEXT:      EMIT ir<%gep4> = getelementptr ir<%p4>, ir<%iv>
; CHECK-NEXT:      EMIT store ir<%phi4>, ir<%gep4>
; CHECK-NEXT:      EMIT ir<%iv.next> = add ir<%iv>, ir<1>
; CHECK-NEXT:      EMIT ir<%ec> = icmp eq ir<%iv.next>, ir<%n>
; CHECK-NEXT:      EMIT vp<%index.next> = add nuw vp<[[VP3]]>, vp<[[VP1:%[0-9]+]]>
; CHECK-NEXT:      EMIT branch-on-count vp<%index.next>, vp<[[VP2:%[0-9]+]]>
; CHECK-NEXT:    No successors
; CHECK-NEXT:  }
; CHECK-NEXT:  Successor(s): middle.block
;
entry:
  br label %loop

loop:
  %iv = phi i32 [0, %entry], [%iv.next, %latch]
  br i1 %c1, label %exiting1, label %exiting2

exiting1:
  br i1 %ee1, label %latch, label %join1

exiting2:
  br i1 %ee2, label %latch, label %join1

join1:
  %phi1.join1 = phi i32 [1, %exiting1], [0, %exiting2]
  %phi2.join1 = phi i32 [0, %exiting1], [1, %exiting2]
  br i1 %c2, label %exiting3, label %exiting4

exiting3:
  br i1 %ee3, label %latch, label %join2

exiting4:
  br i1 %ee4, label %latch, label %join2

join2:
  %phi3.join2 = phi i32 [1, %exiting3], [0, %exiting4]
  %phi4.join2 = phi i32 [0, %exiting3], [1, %exiting4]
  br label %latch

latch:
  %phi1 = phi i32 [1, %exiting1], [0, %exiting2], [%phi1.join1, %exiting3], [%phi1.join1, %exiting4], [%phi1.join1, %join2]
  %phi2 = phi i32 [poison, %exiting1], [1, %exiting2], [%phi2.join1, %exiting3], [%phi2.join1, %exiting4], [%phi2.join1, %join2]
  %phi3 = phi i32 [poison, %exiting1], [poison, %exiting2], [1, %exiting3], [0, %exiting4], [%phi3.join2, %join2]
  %phi4 = phi i32 [poison, %exiting1], [poison, %exiting2], [poison, %exiting3], [1, %exiting4], [%phi4.join2, %join2]
  %gep1 = getelementptr i32, ptr %p1, i32 %iv
  store i32 %phi1, ptr %gep1
  %gep2 = getelementptr i32, ptr %p2, i32 %iv
  store i32 %phi2, ptr %gep2
  %gep3 = getelementptr i32, ptr %p3, i32 %iv
  store i32 %phi3, ptr %gep3
  %gep4 = getelementptr i32, ptr %p4, i32 %iv
  store i32 %phi4, ptr %gep4
  %iv.next = add i32 %iv, 1
  %ec = icmp eq i32 %iv.next, %n
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}
