; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple aarch64 < %s | FileCheck %s --check-prefix=NEON
; RUN: llc -mtriple aarch64 -mattr=+sve < %s | FileCheck %s --check-prefix=SVE

; Legal
define <4 x i32> @srem_v4i32(<4 x i32> %x, <4 x i32> %y, <4 x i1> %m) {
; NEON-LABEL: srem_v4i32:
; NEON:       // %bb.0:
; NEON-NEXT:    shl v2.4h, v2.4h, #15
; NEON-NEXT:    mov w9, v1.s[1]
; NEON-NEXT:    fmov w12, s1
; NEON-NEXT:    mov w10, v0.s[1]
; NEON-NEXT:    mov w15, v1.s[2]
; NEON-NEXT:    mov w16, v0.s[2]
; NEON-NEXT:    mov w18, v1.s[3]
; NEON-NEXT:    mov w0, v0.s[3]
; NEON-NEXT:    cmlt v2.4h, v2.4h, #0
; NEON-NEXT:    umov w8, v2.h[1]
; NEON-NEXT:    umov w11, v2.h[0]
; NEON-NEXT:    umov w14, v2.h[2]
; NEON-NEXT:    umov w17, v2.h[3]
; NEON-NEXT:    tst w8, #0xffff
; NEON-NEXT:    csinc w8, w9, wzr, ne
; NEON-NEXT:    tst w11, #0xffff
; NEON-NEXT:    fmov w11, s0
; NEON-NEXT:    csinc w12, w12, wzr, ne
; NEON-NEXT:    sdiv w9, w10, w8
; NEON-NEXT:    tst w14, #0xffff
; NEON-NEXT:    csinc w14, w15, wzr, ne
; NEON-NEXT:    tst w17, #0xffff
; NEON-NEXT:    sdiv w13, w11, w12
; NEON-NEXT:    msub w8, w9, w8, w10
; NEON-NEXT:    sdiv w15, w16, w14
; NEON-NEXT:    msub w11, w13, w12, w11
; NEON-NEXT:    csinc w12, w18, wzr, ne
; NEON-NEXT:    fmov s0, w11
; NEON-NEXT:    mov v0.s[1], w8
; NEON-NEXT:    sdiv w9, w0, w12
; NEON-NEXT:    msub w8, w15, w14, w16
; NEON-NEXT:    mov v0.s[2], w8
; NEON-NEXT:    msub w8, w9, w12, w0
; NEON-NEXT:    mov v0.s[3], w8
; NEON-NEXT:    ret
;
; SVE-LABEL: srem_v4i32:
; SVE:       // %bb.0:
; SVE-NEXT:    shl v2.4h, v2.4h, #15
; SVE-NEXT:    mov w9, v1.s[1]
; SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; SVE-NEXT:    mov w11, v1.s[2]
; SVE-NEXT:    ptrue p0.s, vl4
; SVE-NEXT:    cmlt v2.4h, v2.4h, #0
; SVE-NEXT:    umov w8, v2.h[1]
; SVE-NEXT:    umov w10, v2.h[0]
; SVE-NEXT:    tst w8, #0xffff
; SVE-NEXT:    csinc w8, w9, wzr, ne
; SVE-NEXT:    fmov w9, s1
; SVE-NEXT:    tst w10, #0xffff
; SVE-NEXT:    umov w10, v2.h[2]
; SVE-NEXT:    csinc w9, w9, wzr, ne
; SVE-NEXT:    fmov s3, w9
; SVE-NEXT:    mov w9, v1.s[3]
; SVE-NEXT:    tst w10, #0xffff
; SVE-NEXT:    csinc w10, w11, wzr, ne
; SVE-NEXT:    mov v3.s[1], w8
; SVE-NEXT:    umov w8, v2.h[3]
; SVE-NEXT:    mov v3.s[2], w10
; SVE-NEXT:    tst w8, #0xffff
; SVE-NEXT:    csinc w8, w9, wzr, ne
; SVE-NEXT:    mov v3.s[3], w8
; SVE-NEXT:    movprfx z1, z0
; SVE-NEXT:    sdiv z1.s, p0/m, z1.s, z3.s
; SVE-NEXT:    mls v0.4s, v1.4s, v3.4s
; SVE-NEXT:    // kill: def $q0 killed $q0 killed $z0
; SVE-NEXT:    ret
  %res = call <4 x i32> @llvm.masked.srem(<4 x i32> %x, <4 x i32> %y, <4 x i1> %m)
  ret <4 x i32> %res
}

define <2 x i64> @srem_v2i64(<2 x i64> %x, <2 x i64> %y, <2 x i1> %m) {
; NEON-LABEL: srem_v2i64:
; NEON:       // %bb.0:
; NEON-NEXT:    shl v2.2s, v2.2s, #31
; NEON-NEXT:    mov x9, v1.d[1]
; NEON-NEXT:    mov x12, v0.d[1]
; NEON-NEXT:    cmlt v2.2s, v2.2s, #0
; NEON-NEXT:    mov w8, v2.s[1]
; NEON-NEXT:    fmov w10, s2
; NEON-NEXT:    cmp w8, #0
; NEON-NEXT:    fmov x8, d1
; NEON-NEXT:    csinc x9, x9, xzr, ne
; NEON-NEXT:    cmp w10, #0
; NEON-NEXT:    fmov x10, d0
; NEON-NEXT:    sdiv x13, x12, x9
; NEON-NEXT:    csinc x8, x8, xzr, ne
; NEON-NEXT:    sdiv x11, x10, x8
; NEON-NEXT:    msub x9, x13, x9, x12
; NEON-NEXT:    msub x8, x11, x8, x10
; NEON-NEXT:    fmov d0, x8
; NEON-NEXT:    mov v0.d[1], x9
; NEON-NEXT:    ret
;
; SVE-LABEL: srem_v2i64:
; SVE:       // %bb.0:
; SVE-NEXT:    shl v2.2s, v2.2s, #31
; SVE-NEXT:    mov x9, v1.d[1]
; SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; SVE-NEXT:    fmov x10, d1
; SVE-NEXT:    ptrue p0.d, vl2
; SVE-NEXT:    cmlt v2.2s, v2.2s, #0
; SVE-NEXT:    mov w8, v2.s[1]
; SVE-NEXT:    cmp w8, #0
; SVE-NEXT:    fmov w8, s2
; SVE-NEXT:    csinc x9, x9, xzr, ne
; SVE-NEXT:    cmp w8, #0
; SVE-NEXT:    csinc x8, x10, xzr, ne
; SVE-NEXT:    fmov d1, x8
; SVE-NEXT:    mov v1.d[1], x9
; SVE-NEXT:    movprfx z2, z0
; SVE-NEXT:    sdiv z2.d, p0/m, z2.d, z1.d
; SVE-NEXT:    mls z0.d, p0/m, z2.d, z1.d
; SVE-NEXT:    // kill: def $q0 killed $q0 killed $z0
; SVE-NEXT:    ret
  %res = call <2 x i64> @llvm.masked.srem(<2 x i64> %x, <2 x i64> %y, <2 x i1> %m)
  ret <2 x i64> %res
}

; Splitting
define <4 x i64> @srem_v4i64(<4 x i64> %x, <4 x i64> %y, <4 x i1> %m) {
; NEON-LABEL: srem_v4i64:
; NEON:       // %bb.0:
; NEON-NEXT:    ushll v4.4s, v4.4h, #0
; NEON-NEXT:    mov x9, v2.d[1]
; NEON-NEXT:    mov x10, v0.d[1]
; NEON-NEXT:    fmov x12, d2
; NEON-NEXT:    mov x15, v3.d[1]
; NEON-NEXT:    fmov x16, d3
; NEON-NEXT:    mov x18, v1.d[1]
; NEON-NEXT:    shl v5.2s, v4.2s, #31
; NEON-NEXT:    cmlt v5.2s, v5.2s, #0
; NEON-NEXT:    mov w8, v5.s[1]
; NEON-NEXT:    fmov w11, s5
; NEON-NEXT:    cmp w8, #0
; NEON-NEXT:    csinc x8, x9, xzr, ne
; NEON-NEXT:    cmp w11, #0
; NEON-NEXT:    fmov x11, d0
; NEON-NEXT:    ext v0.16b, v4.16b, v4.16b, #8
; NEON-NEXT:    csinc x12, x12, xzr, ne
; NEON-NEXT:    sdiv x9, x10, x8
; NEON-NEXT:    shl v0.2s, v0.2s, #31
; NEON-NEXT:    cmlt v0.2s, v0.2s, #0
; NEON-NEXT:    mov w14, v0.s[1]
; NEON-NEXT:    cmp w14, #0
; NEON-NEXT:    fmov w14, s0
; NEON-NEXT:    csinc x15, x15, xzr, ne
; NEON-NEXT:    sdiv x13, x11, x12
; NEON-NEXT:    msub x8, x9, x8, x10
; NEON-NEXT:    cmp w14, #0
; NEON-NEXT:    csinc x14, x16, xzr, ne
; NEON-NEXT:    fmov x16, d1
; NEON-NEXT:    sdiv x17, x16, x14
; NEON-NEXT:    msub x9, x13, x12, x11
; NEON-NEXT:    fmov d0, x9
; NEON-NEXT:    mov v0.d[1], x8
; NEON-NEXT:    sdiv x0, x18, x15
; NEON-NEXT:    msub x10, x17, x14, x16
; NEON-NEXT:    fmov d1, x10
; NEON-NEXT:    msub x11, x0, x15, x18
; NEON-NEXT:    mov v1.d[1], x11
; NEON-NEXT:    ret
;
; SVE-LABEL: srem_v4i64:
; SVE:       // %bb.0:
; SVE-NEXT:    ushll v4.4s, v4.4h, #0
; SVE-NEXT:    mov x9, v2.d[1]
; SVE-NEXT:    // kill: def $q1 killed $q1 def $z1
; SVE-NEXT:    // kill: def $q0 killed $q0 def $z0
; SVE-NEXT:    ptrue p0.d, vl2
; SVE-NEXT:    shl v5.2s, v4.2s, #31
; SVE-NEXT:    ext v4.16b, v4.16b, v4.16b, #8
; SVE-NEXT:    cmlt v5.2s, v5.2s, #0
; SVE-NEXT:    shl v4.2s, v4.2s, #31
; SVE-NEXT:    mov w8, v5.s[1]
; SVE-NEXT:    fmov w10, s5
; SVE-NEXT:    cmlt v4.2s, v4.2s, #0
; SVE-NEXT:    cmp w8, #0
; SVE-NEXT:    fmov x8, d2
; SVE-NEXT:    csinc x9, x9, xzr, ne
; SVE-NEXT:    cmp w10, #0
; SVE-NEXT:    fmov w10, s4
; SVE-NEXT:    csinc x8, x8, xzr, ne
; SVE-NEXT:    fmov d2, x8
; SVE-NEXT:    mov w8, v4.s[1]
; SVE-NEXT:    mov v2.d[1], x9
; SVE-NEXT:    mov x9, v3.d[1]
; SVE-NEXT:    cmp w8, #0
; SVE-NEXT:    fmov x8, d3
; SVE-NEXT:    csinc x9, x9, xzr, ne
; SVE-NEXT:    cmp w10, #0
; SVE-NEXT:    movprfx z5, z0
; SVE-NEXT:    sdiv z5.d, p0/m, z5.d, z2.d
; SVE-NEXT:    csinc x8, x8, xzr, ne
; SVE-NEXT:    fmov d3, x8
; SVE-NEXT:    mov v3.d[1], x9
; SVE-NEXT:    movprfx z4, z1
; SVE-NEXT:    sdiv z4.d, p0/m, z4.d, z3.d
; SVE-NEXT:    mls z0.d, p0/m, z5.d, z2.d
; SVE-NEXT:    // kill: def $q0 killed $q0 killed $z0
; SVE-NEXT:    mls z1.d, p0/m, z4.d, z3.d
; SVE-NEXT:    // kill: def $q1 killed $q1 killed $z1
; SVE-NEXT:    ret
  %res = call <4 x i64> @llvm.masked.srem(<4 x i64> %x, <4 x i64> %y, <4 x i1> %m)
  ret <4 x i64> %res
}

; Widening
define <2 x i32> @srem_v2i32(<2 x i32> %x, <2 x i32> %y, <2 x i1> %m) {
; NEON-LABEL: srem_v2i32:
; NEON:       // %bb.0:
; NEON-NEXT:    shl v2.2s, v2.2s, #31
; NEON-NEXT:    // kill: def $d0 killed $d0 def $q0
; NEON-NEXT:    fmov w8, s0
; NEON-NEXT:    mov w11, v0.s[1]
; NEON-NEXT:    cmlt v2.2s, v2.2s, #0
; NEON-NEXT:    and v1.8b, v1.8b, v2.8b
; NEON-NEXT:    mvn v2.8b, v2.8b
; NEON-NEXT:    sub v1.2s, v1.2s, v2.2s
; NEON-NEXT:    fmov w9, s1
; NEON-NEXT:    mov w12, v1.s[1]
; NEON-NEXT:    sdiv w10, w8, w9
; NEON-NEXT:    sdiv w13, w11, w12
; NEON-NEXT:    msub w8, w10, w9, w8
; NEON-NEXT:    fmov s0, w8
; NEON-NEXT:    msub w9, w13, w12, w11
; NEON-NEXT:    mov v0.s[1], w9
; NEON-NEXT:    // kill: def $d0 killed $d0 killed $q0
; NEON-NEXT:    ret
;
; SVE-LABEL: srem_v2i32:
; SVE:       // %bb.0:
; SVE-NEXT:    shl v2.2s, v2.2s, #31
; SVE-NEXT:    ptrue p0.s, vl2
; SVE-NEXT:    // kill: def $d0 killed $d0 def $z0
; SVE-NEXT:    cmlt v2.2s, v2.2s, #0
; SVE-NEXT:    and v1.8b, v1.8b, v2.8b
; SVE-NEXT:    mvn v2.8b, v2.8b
; SVE-NEXT:    sub v1.2s, v1.2s, v2.2s
; SVE-NEXT:    movprfx z2, z0
; SVE-NEXT:    sdiv z2.s, p0/m, z2.s, z1.s
; SVE-NEXT:    mls v0.2s, v2.2s, v1.2s
; SVE-NEXT:    // kill: def $d0 killed $d0 killed $z0
; SVE-NEXT:    ret
  %res = call <2 x i32> @llvm.masked.srem(<2 x i32> %x, <2 x i32> %y, <2 x i1> %m)
  ret <2 x i32> %res
}

; Promotion
define <4 x i16> @srem_v4i16(<4 x i16> %x, <4 x i16> %y, <4 x i1> %m) {
; NEON-LABEL: srem_v4i16:
; NEON:       // %bb.0:
; NEON-NEXT:    shl v2.4h, v2.4h, #15
; NEON-NEXT:    // kill: def $d0 killed $d0 def $q0
; NEON-NEXT:    smov w11, v0.h[0]
; NEON-NEXT:    smov w8, v0.h[1]
; NEON-NEXT:    smov w14, v0.h[2]
; NEON-NEXT:    smov w17, v0.h[3]
; NEON-NEXT:    cmlt v2.4h, v2.4h, #0
; NEON-NEXT:    and v1.8b, v1.8b, v2.8b
; NEON-NEXT:    mvn v2.8b, v2.8b
; NEON-NEXT:    sub v1.4h, v1.4h, v2.4h
; NEON-NEXT:    smov w12, v1.h[0]
; NEON-NEXT:    smov w9, v1.h[1]
; NEON-NEXT:    smov w15, v1.h[2]
; NEON-NEXT:    smov w18, v1.h[3]
; NEON-NEXT:    sdiv w13, w11, w12
; NEON-NEXT:    sdiv w10, w8, w9
; NEON-NEXT:    msub w11, w13, w12, w11
; NEON-NEXT:    fmov s0, w11
; NEON-NEXT:    sdiv w16, w14, w15
; NEON-NEXT:    msub w8, w10, w9, w8
; NEON-NEXT:    mov v0.h[1], w8
; NEON-NEXT:    sdiv w9, w17, w18
; NEON-NEXT:    msub w8, w16, w15, w14
; NEON-NEXT:    mov v0.h[2], w8
; NEON-NEXT:    msub w8, w9, w18, w17
; NEON-NEXT:    mov v0.h[3], w8
; NEON-NEXT:    // kill: def $d0 killed $d0 killed $q0
; NEON-NEXT:    ret
;
; SVE-LABEL: srem_v4i16:
; SVE:       // %bb.0:
; SVE-NEXT:    shl v2.4h, v2.4h, #15
; SVE-NEXT:    ptrue p0.s, vl4
; SVE-NEXT:    cmlt v2.4h, v2.4h, #0
; SVE-NEXT:    and v1.8b, v1.8b, v2.8b
; SVE-NEXT:    mvn v2.8b, v2.8b
; SVE-NEXT:    sub v1.4h, v1.4h, v2.4h
; SVE-NEXT:    sshll v2.4s, v0.4h, #0
; SVE-NEXT:    sshll v3.4s, v1.4h, #0
; SVE-NEXT:    sdiv z2.s, p0/m, z2.s, z3.s
; SVE-NEXT:    xtn v2.4h, v2.4s
; SVE-NEXT:    mls v0.4h, v2.4h, v1.4h
; SVE-NEXT:    ret
  %res = call <4 x i16> @llvm.masked.srem(<4 x i16> %x, <4 x i16> %y, <4 x i1> %m)
  ret <4 x i16> %res
}

; Scalarization
define <1 x i64> @srem_v1i164(<1 x i64> %x, <1 x i64> %y, <1 x i1> %m) {
; NEON-LABEL: srem_v1i164:
; NEON:       // %bb.0:
; NEON-NEXT:    // kill: def $d1 killed $d1 def $q1
; NEON-NEXT:    fmov x8, d1
; NEON-NEXT:    // kill: def $d0 killed $d0 def $q0
; NEON-NEXT:    fmov x9, d0
; NEON-NEXT:    tst w0, #0x1
; NEON-NEXT:    csinc x8, x8, xzr, ne
; NEON-NEXT:    sdiv x10, x9, x8
; NEON-NEXT:    msub x8, x10, x8, x9
; NEON-NEXT:    fmov d0, x8
; NEON-NEXT:    ret
;
; SVE-LABEL: srem_v1i164:
; SVE:       // %bb.0:
; SVE-NEXT:    // kill: def $d1 killed $d1 def $q1
; SVE-NEXT:    fmov x8, d1
; SVE-NEXT:    // kill: def $d0 killed $d0 def $q0
; SVE-NEXT:    fmov x9, d0
; SVE-NEXT:    tst w0, #0x1
; SVE-NEXT:    csinc x8, x8, xzr, ne
; SVE-NEXT:    sdiv x10, x9, x8
; SVE-NEXT:    msub x8, x10, x8, x9
; SVE-NEXT:    fmov d0, x8
; SVE-NEXT:    ret
  %res = call <1 x i64> @llvm.masked.srem(<1 x i64> %x, <1 x i64> %y, <1 x i1> %m)
  ret <1 x i64> %res
}

; Expansion
define <2 x i128> @srem_v2i128(<2 x i128> %x, <2 x i128> %y, <2 x i1> %m) {
; NEON-LABEL: srem_v2i128:
; NEON:       // %bb.0:
; NEON-NEXT:    stp x30, x25, [sp, #-64]! // 16-byte Folded Spill
; NEON-NEXT:    stp x24, x23, [sp, #16] // 16-byte Folded Spill
; NEON-NEXT:    stp x22, x21, [sp, #32] // 16-byte Folded Spill
; NEON-NEXT:    stp x20, x19, [sp, #48] // 16-byte Folded Spill
; NEON-NEXT:    .cfi_def_cfa_offset 64
; NEON-NEXT:    .cfi_offset w19, -8
; NEON-NEXT:    .cfi_offset w20, -16
; NEON-NEXT:    .cfi_offset w21, -24
; NEON-NEXT:    .cfi_offset w22, -32
; NEON-NEXT:    .cfi_offset w23, -40
; NEON-NEXT:    .cfi_offset w24, -48
; NEON-NEXT:    .cfi_offset w25, -56
; NEON-NEXT:    .cfi_offset w30, -64
; NEON-NEXT:    // kill: def $d0 killed $d0 def $q0
; NEON-NEXT:    fmov w8, s0
; NEON-NEXT:    mov x21, x3
; NEON-NEXT:    mov x22, x2
; NEON-NEXT:    mov x19, x7
; NEON-NEXT:    mov x20, x6
; NEON-NEXT:    mov w25, v0.s[1]
; NEON-NEXT:    tst w8, #0x1
; NEON-NEXT:    csel x3, x5, xzr, ne
; NEON-NEXT:    csinc x2, x4, xzr, ne
; NEON-NEXT:    bl __modti3
; NEON-NEXT:    tst w25, #0x1
; NEON-NEXT:    mov x23, x0
; NEON-NEXT:    mov x24, x1
; NEON-NEXT:    csel x3, x19, xzr, ne
; NEON-NEXT:    csinc x2, x20, xzr, ne
; NEON-NEXT:    mov x0, x22
; NEON-NEXT:    mov x1, x21
; NEON-NEXT:    bl __modti3
; NEON-NEXT:    mov x2, x0
; NEON-NEXT:    mov x3, x1
; NEON-NEXT:    mov x0, x23
; NEON-NEXT:    mov x1, x24
; NEON-NEXT:    ldp x20, x19, [sp, #48] // 16-byte Folded Reload
; NEON-NEXT:    ldp x22, x21, [sp, #32] // 16-byte Folded Reload
; NEON-NEXT:    ldp x24, x23, [sp, #16] // 16-byte Folded Reload
; NEON-NEXT:    ldp x30, x25, [sp], #64 // 16-byte Folded Reload
; NEON-NEXT:    ret
;
; SVE-LABEL: srem_v2i128:
; SVE:       // %bb.0:
; SVE-NEXT:    stp x30, x25, [sp, #-64]! // 16-byte Folded Spill
; SVE-NEXT:    stp x24, x23, [sp, #16] // 16-byte Folded Spill
; SVE-NEXT:    stp x22, x21, [sp, #32] // 16-byte Folded Spill
; SVE-NEXT:    stp x20, x19, [sp, #48] // 16-byte Folded Spill
; SVE-NEXT:    .cfi_def_cfa_offset 64
; SVE-NEXT:    .cfi_offset w19, -8
; SVE-NEXT:    .cfi_offset w20, -16
; SVE-NEXT:    .cfi_offset w21, -24
; SVE-NEXT:    .cfi_offset w22, -32
; SVE-NEXT:    .cfi_offset w23, -40
; SVE-NEXT:    .cfi_offset w24, -48
; SVE-NEXT:    .cfi_offset w25, -56
; SVE-NEXT:    .cfi_offset w30, -64
; SVE-NEXT:    // kill: def $d0 killed $d0 def $q0
; SVE-NEXT:    fmov w8, s0
; SVE-NEXT:    mov x21, x3
; SVE-NEXT:    mov x22, x2
; SVE-NEXT:    mov x19, x7
; SVE-NEXT:    mov x20, x6
; SVE-NEXT:    mov w25, v0.s[1]
; SVE-NEXT:    tst w8, #0x1
; SVE-NEXT:    csel x3, x5, xzr, ne
; SVE-NEXT:    csinc x2, x4, xzr, ne
; SVE-NEXT:    bl __modti3
; SVE-NEXT:    tst w25, #0x1
; SVE-NEXT:    mov x23, x0
; SVE-NEXT:    mov x24, x1
; SVE-NEXT:    csel x3, x19, xzr, ne
; SVE-NEXT:    csinc x2, x20, xzr, ne
; SVE-NEXT:    mov x0, x22
; SVE-NEXT:    mov x1, x21
; SVE-NEXT:    bl __modti3
; SVE-NEXT:    mov x2, x0
; SVE-NEXT:    mov x3, x1
; SVE-NEXT:    mov x0, x23
; SVE-NEXT:    mov x1, x24
; SVE-NEXT:    ldp x20, x19, [sp, #48] // 16-byte Folded Reload
; SVE-NEXT:    ldp x22, x21, [sp, #32] // 16-byte Folded Reload
; SVE-NEXT:    ldp x24, x23, [sp, #16] // 16-byte Folded Reload
; SVE-NEXT:    ldp x30, x25, [sp], #64 // 16-byte Folded Reload
; SVE-NEXT:    ret
  %res = call <2 x i128> @llvm.masked.srem(<2 x i128> %x, <2 x i128> %y, <2 x i1> %m)
  ret <2 x i128> %res
}

; Promotion and widening
define <3 x i10> @srem_v3i10(<3 x i10> %x, <3 x i10> %y, <3 x i1> %m) {
; NEON-LABEL: srem_v3i10:
; NEON:       // %bb.0:
; NEON-NEXT:    fmov s0, w6
; NEON-NEXT:    fmov s1, w3
; NEON-NEXT:    ldr w8, [sp]
; NEON-NEXT:    fmov s2, w0
; NEON-NEXT:    mov v0.h[1], w7
; NEON-NEXT:    mov v1.h[1], w4
; NEON-NEXT:    mov v2.h[1], w1
; NEON-NEXT:    mov v0.h[2], w8
; NEON-NEXT:    mov v1.h[2], w5
; NEON-NEXT:    mov v2.h[2], w2
; NEON-NEXT:    shl v0.4h, v0.4h, #15
; NEON-NEXT:    shl v1.4h, v1.4h, #6
; NEON-NEXT:    shl v2.4h, v2.4h, #6
; NEON-NEXT:    cmlt v0.4h, v0.4h, #0
; NEON-NEXT:    sshr v1.4h, v1.4h, #6
; NEON-NEXT:    sshr v2.4h, v2.4h, #6
; NEON-NEXT:    and v1.8b, v1.8b, v0.8b
; NEON-NEXT:    mvn v0.8b, v0.8b
; NEON-NEXT:    smov w8, v2.h[0]
; NEON-NEXT:    smov w11, v2.h[1]
; NEON-NEXT:    smov w14, v2.h[2]
; NEON-NEXT:    sub v0.4h, v1.4h, v0.4h
; NEON-NEXT:    smov w9, v0.h[0]
; NEON-NEXT:    smov w12, v0.h[1]
; NEON-NEXT:    smov w15, v0.h[2]
; NEON-NEXT:    sdiv w10, w8, w9
; NEON-NEXT:    sdiv w13, w11, w12
; NEON-NEXT:    msub w0, w10, w9, w8
; NEON-NEXT:    sdiv w16, w14, w15
; NEON-NEXT:    msub w1, w13, w12, w11
; NEON-NEXT:    msub w2, w16, w15, w14
; NEON-NEXT:    ret
;
; SVE-LABEL: srem_v3i10:
; SVE:       // %bb.0:
; SVE-NEXT:    fmov s0, w6
; SVE-NEXT:    fmov s1, w3
; SVE-NEXT:    ldr w8, [sp]
; SVE-NEXT:    fmov s2, w0
; SVE-NEXT:    ptrue p0.s, vl4
; SVE-NEXT:    mov v0.h[1], w7
; SVE-NEXT:    mov v1.h[1], w4
; SVE-NEXT:    mov v2.h[1], w1
; SVE-NEXT:    mov v0.h[2], w8
; SVE-NEXT:    mov v1.h[2], w5
; SVE-NEXT:    mov v2.h[2], w2
; SVE-NEXT:    shl v0.4h, v0.4h, #15
; SVE-NEXT:    shl v1.4h, v1.4h, #6
; SVE-NEXT:    shl v2.4h, v2.4h, #6
; SVE-NEXT:    cmlt v0.4h, v0.4h, #0
; SVE-NEXT:    sshr v1.4h, v1.4h, #6
; SVE-NEXT:    sshr v2.4h, v2.4h, #6
; SVE-NEXT:    and v1.8b, v1.8b, v0.8b
; SVE-NEXT:    mvn v0.8b, v0.8b
; SVE-NEXT:    sshll v3.4s, v2.4h, #0
; SVE-NEXT:    sub v0.4h, v1.4h, v0.4h
; SVE-NEXT:    sshll v1.4s, v0.4h, #0
; SVE-NEXT:    sdivr z1.s, p0/m, z1.s, z3.s
; SVE-NEXT:    xtn v1.4h, v1.4s
; SVE-NEXT:    mls v2.4h, v1.4h, v0.4h
; SVE-NEXT:    umov w0, v2.h[0]
; SVE-NEXT:    umov w1, v2.h[1]
; SVE-NEXT:    umov w2, v2.h[2]
; SVE-NEXT:    ret
  %res = call <3 x i10> @llvm.masked.srem(<3 x i10> %x, <3 x i10> %y, <3 x i1> %m)
  ret <3 x i10> %res
}
