set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER $ENV{GITHUB_WORKSPACE}/llvm-project/build/bin/clang)
set(CMAKE_CXX_COMPILER $ENV{GITHUB_WORKSPACE}/llvm-project/build/bin/clang++)
set(CMAKE_C_COMPILER_TARGET riscv64-linux-gnu)
set(CMAKE_CXX_COMPILER_TARGET riscv64-linux-gnu)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -march=rva23u64 -save-temps=obj" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=rva23u64 -save-temps=obj" CACHE STRING "" FORCE)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(CMAKE_LINKER_TYPE LLD)
