; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt < %s -S -p loop-vectorize -mtriple riscv64 -mattr=+v | FileCheck %s --check-prefix=RV64
; RUN: opt < %s -S -p loop-vectorize -mtriple riscv32 -mattr=+v | FileCheck %s --check-prefix=RV32
; RUN: opt < %s -S -p loop-vectorize -mtriple riscv32 -mattr=+zve32x,+zvl128b | FileCheck %s --check-prefix=ZVE32X

; Make sure that we generate a VPInstruction::FirstActiveLane that matches the
; targets index type, i.e. i64 on RV64 and i32 on RV32.  Otherwise on rv32 with
; zve32x we return an invalid cost for cttz.elts with scalable VFs.

declare void @init_mem(ptr)

define i32 @early_exit_live_out() {
; RV64-LABEL: define i32 @early_exit_live_out(
; RV64-SAME: ) #[[ATTR0:[0-9]+]] {
; RV64-NEXT:  [[ENTRY:.*]]:
; RV64-NEXT:    [[P:%.*]] = alloca [1024 x i32], align 4
; RV64-NEXT:    call void @init_mem(ptr [[P]])
; RV64-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; RV64-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; RV64-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; RV64-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; RV64:       [[VECTOR_PH]]:
; RV64-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; RV64-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 2
; RV64-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; RV64-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; RV64-NEXT:    br label %[[LOOP:.*]]
; RV64:       [[LOOP]]:
; RV64-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; RV64-NEXT:    [[TMP4:%.*]] = getelementptr i32, ptr [[P]], i64 [[INDEX]]
; RV64-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP4]], align 4
; RV64-NEXT:    [[TMP5:%.*]] = icmp ne <vscale x 4 x i32> [[WIDE_LOAD]], zeroinitializer
; RV64-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; RV64-NEXT:    [[TMP6:%.*]] = freeze <vscale x 4 x i1> [[TMP5]]
; RV64-NEXT:    [[TMP7:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP6]])
; RV64-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; RV64-NEXT:    br i1 [[TMP7]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[VECTOR_BODY_INTERIM]]
; RV64:       [[VECTOR_BODY_INTERIM]]:
; RV64-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK:.*]], label %[[LOOP]], !llvm.loop [[LOOP0:![0-9]+]]
; RV64:       [[MIDDLE_BLOCK]]:
; RV64-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; RV64-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; RV64:       [[VECTOR_EARLY_EXIT]]:
; RV64-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.nxv4i1(<vscale x 4 x i1> [[TMP5]], i1 false)
; RV64-NEXT:    [[TMP9:%.*]] = extractelement <vscale x 4 x i32> [[WIDE_LOAD]], i64 [[FIRST_ACTIVE_LANE]]
; RV64-NEXT:    br label %[[EXIT]]
; RV64:       [[SCALAR_PH]]:
; RV64-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; RV64-NEXT:    br label %[[LOOP1:.*]]
; RV64:       [[LOOP1]]:
; RV64-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; RV64-NEXT:    [[GEP:%.*]] = getelementptr i32, ptr [[P]], i64 [[IV]]
; RV64-NEXT:    [[LD:%.*]] = load i32, ptr [[GEP]], align 4
; RV64-NEXT:    [[C:%.*]] = icmp eq i32 [[LD]], 0
; RV64-NEXT:    br i1 [[C]], label %[[LATCH]], label %[[EXIT]]
; RV64:       [[LATCH]]:
; RV64-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 1
; RV64-NEXT:    [[EC:%.*]] = icmp eq i64 [[IV_NEXT]], 1024
; RV64-NEXT:    br i1 [[EC]], label %[[EXIT]], label %[[LOOP1]], !llvm.loop [[LOOP3:![0-9]+]]
; RV64:       [[EXIT]]:
; RV64-NEXT:    [[RET:%.*]] = phi i32 [ [[LD]], %[[LOOP1]] ], [ 0, %[[LATCH]] ], [ 0, %[[MIDDLE_BLOCK]] ], [ [[TMP9]], %[[VECTOR_EARLY_EXIT]] ]
; RV64-NEXT:    ret i32 [[RET]]
;
; RV32-LABEL: define i32 @early_exit_live_out(
; RV32-SAME: ) #[[ATTR0:[0-9]+]] {
; RV32-NEXT:  [[ENTRY:.*]]:
; RV32-NEXT:    [[P:%.*]] = alloca [1024 x i32], align 4
; RV32-NEXT:    call void @init_mem(ptr [[P]])
; RV32-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; RV32-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; RV32-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; RV32-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; RV32:       [[VECTOR_PH]]:
; RV32-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; RV32-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 2
; RV32-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; RV32-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; RV32-NEXT:    br label %[[VECTOR_BODY:.*]]
; RV32:       [[VECTOR_BODY]]:
; RV32-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; RV32-NEXT:    [[TMP4:%.*]] = getelementptr i32, ptr [[P]], i64 [[INDEX]]
; RV32-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP4]], align 4
; RV32-NEXT:    [[TMP5:%.*]] = icmp ne <vscale x 4 x i32> [[WIDE_LOAD]], zeroinitializer
; RV32-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; RV32-NEXT:    [[TMP6:%.*]] = freeze <vscale x 4 x i1> [[TMP5]]
; RV32-NEXT:    [[TMP7:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP6]])
; RV32-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; RV32-NEXT:    br i1 [[TMP7]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[VECTOR_BODY_INTERIM]]
; RV32:       [[VECTOR_BODY_INTERIM]]:
; RV32-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; RV32:       [[MIDDLE_BLOCK]]:
; RV32-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; RV32-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; RV32:       [[VECTOR_EARLY_EXIT]]:
; RV32-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.nxv4i1(<vscale x 4 x i1> [[TMP5]], i1 false)
; RV32-NEXT:    [[TMP9:%.*]] = extractelement <vscale x 4 x i32> [[WIDE_LOAD]], i64 [[FIRST_ACTIVE_LANE]]
; RV32-NEXT:    br label %[[EXIT]]
; RV32:       [[SCALAR_PH]]:
; RV32-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; RV32-NEXT:    br label %[[LOOP:.*]]
; RV32:       [[LOOP]]:
; RV32-NEXT:    [[IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; RV32-NEXT:    [[GEP:%.*]] = getelementptr i32, ptr [[P]], i64 [[IV]]
; RV32-NEXT:    [[LD:%.*]] = load i32, ptr [[GEP]], align 4
; RV32-NEXT:    [[C:%.*]] = icmp eq i32 [[LD]], 0
; RV32-NEXT:    br i1 [[C]], label %[[LATCH]], label %[[EXIT]]
; RV32:       [[LATCH]]:
; RV32-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 1
; RV32-NEXT:    [[EC:%.*]] = icmp eq i64 [[IV_NEXT]], 1024
; RV32-NEXT:    br i1 [[EC]], label %[[EXIT]], label %[[LOOP]], !llvm.loop [[LOOP3:![0-9]+]]
; RV32:       [[EXIT]]:
; RV32-NEXT:    [[RET:%.*]] = phi i32 [ [[LD]], %[[LOOP]] ], [ 0, %[[LATCH]] ], [ 0, %[[MIDDLE_BLOCK]] ], [ [[TMP9]], %[[VECTOR_EARLY_EXIT]] ]
; RV32-NEXT:    ret i32 [[RET]]
;
; ZVE32X-LABEL: define i32 @early_exit_live_out(
; ZVE32X-SAME: ) #[[ATTR0:[0-9]+]] {
; ZVE32X-NEXT:  [[ENTRY:.*:]]
; ZVE32X-NEXT:    [[P:%.*]] = alloca [1024 x i32], align 4
; ZVE32X-NEXT:    call void @init_mem(ptr [[P]])
; ZVE32X-NEXT:    br label %[[LOOP:.*]]
; ZVE32X:       [[LOOP]]:
; ZVE32X-NEXT:    br label %[[LATCH:.*]]
; ZVE32X:       [[LATCH]]:
; ZVE32X-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[LOOP]] ], [ [[INDEX_NEXT:%.*]], %[[EXIT:.*]] ]
; ZVE32X-NEXT:    [[TMP0:%.*]] = getelementptr i32, ptr [[P]], i64 [[INDEX]]
; ZVE32X-NEXT:    [[WIDE_LOAD:%.*]] = load <8 x i32>, ptr [[TMP0]], align 4
; ZVE32X-NEXT:    [[TMP1:%.*]] = icmp ne <8 x i32> [[WIDE_LOAD]], zeroinitializer
; ZVE32X-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; ZVE32X-NEXT:    [[TMP2:%.*]] = freeze <8 x i1> [[TMP1]]
; ZVE32X-NEXT:    [[TMP3:%.*]] = call i1 @llvm.vector.reduce.or.v8i1(<8 x i1> [[TMP2]])
; ZVE32X-NEXT:    [[TMP4:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; ZVE32X-NEXT:    br i1 [[TMP3]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[EXIT]]
; ZVE32X:       [[EXIT]]:
; ZVE32X-NEXT:    br i1 [[TMP4]], label %[[MIDDLE_BLOCK:.*]], label %[[LATCH]], !llvm.loop [[LOOP0:![0-9]+]]
; ZVE32X:       [[MIDDLE_BLOCK]]:
; ZVE32X-NEXT:    br label %[[EXIT1:.*]]
; ZVE32X:       [[VECTOR_EARLY_EXIT]]:
; ZVE32X-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v8i1(<8 x i1> [[TMP1]], i1 false)
; ZVE32X-NEXT:    [[TMP5:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 [[FIRST_ACTIVE_LANE]]
; ZVE32X-NEXT:    br label %[[EXIT1]]
; ZVE32X:       [[EXIT1]]:
; ZVE32X-NEXT:    [[RET:%.*]] = phi i32 [ [[TMP5]], %[[VECTOR_EARLY_EXIT]] ], [ 0, %[[MIDDLE_BLOCK]] ]
; ZVE32X-NEXT:    ret i32 [[RET]]
;
entry:
  %p = alloca [1024 x i32]
  call void @init_mem(ptr %p)
  br label %loop

loop:
  %iv = phi i64 [0, %entry], [%iv.next, %latch]
  %gep = getelementptr i32, ptr %p, i64 %iv
  %ld = load i32, ptr %gep
  %c = icmp eq i32 %ld, 0
  br i1 %c, label %latch, label %exit

latch:
  %iv.next = add i64 %iv, 1
  %ec = icmp eq i64 %iv.next, 1024
  br i1 %ec, label %exit, label %loop

exit:
  %ret = phi i32 [ %ld, %loop ], [ 0, %latch ]
  ret i32 %ret
}


; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META2]], [[META1]]}
