; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -prefer-predicate-over-epilogue=predicate-else-scalar-epilogue -mtriple=riscv64 -mattr=+v -S < %s | FileCheck %s

; Test for https://github.com/llvm/llvm-project/issues/199896
; This used to crash because optimizeMaskToEVL would create vp.load/vp.store
; of i1 types, which the RISC-V backend cannot lower (vlm.v/vsm.v have no
; mask operand to represent the EVL mask). The fix is to skip i1 element types
; in optimizeMaskToEVL so they remain as masked loads/stores.

; CHECK-LABEL: define void @copy_bool(
define void @copy_bool(ptr noalias %dst, ptr noalias %src, i64 %n) {
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %src.gep = getelementptr i1, ptr %src, i64 %iv
  %val = load i1, ptr %src.gep, align 1
  %dst.gep = getelementptr i1, ptr %dst, i64 %iv
  store i1 %val, ptr %dst.gep, align 1
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond = icmp eq i64 %iv.next, %n
  br i1 %exitcond, label %for.end, label %for.body

for.end:
  ret void
}
