; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt -p loop-vectorize -mtriple riscv64 -mattr=+v < %s -S | FileCheck %s

define void @reverse_zext(ptr noalias %src, ptr noalias %dst, i32 %n) {
; CHECK-LABEL: define void @reverse_zext(
; CHECK-SAME: ptr noalias [[SRC:%.*]], ptr noalias [[DST:%.*]], i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[VECTOR_PH:.*]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[TMP3:%.*]] = phi i32 [ [[N]], %[[VECTOR_PH]] ], [ [[TMP4:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP4]] = add nsw i32 [[TMP3]], -1
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i32, ptr [[SRC]], i32 [[TMP4]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP5]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i64, ptr [[DST]], i32 [[TMP4]]
; CHECK-NEXT:    store i64 [[TMP6]], ptr [[TMP11]], align 8
; CHECK-NEXT:    [[EC:%.*]] = icmp sgt i32 [[TMP4]], 0
; CHECK-NEXT:    br i1 [[EC]], label %[[VECTOR_BODY]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [%n, %entry], [%iv.next, %loop]
  %iv.next = add nsw i32 %iv, -1
  %gep.src = getelementptr i32, ptr %src, i32 %iv.next
  %x = load i32, ptr %gep.src
  %y = zext i32 %x to i64
  %gep.dst = getelementptr i64, ptr %dst, i32 %iv.next
  store i64 %y, ptr %gep.dst
  %ec = icmp sgt i32 %iv.next, 0
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}
