# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc %s -o - -mtriple=riscv64 -mattr=+v -run-pass=riscv-fold-masks \
# RUN:     -verify-machineinstrs | FileCheck %s

---
name: vmsleu_vi
body: |
  bb.0:
    liveins: $v8, $v9
    ; CHECK-LABEL: name: vmsleu_vi
    ; CHECK: liveins: $v8, $v9
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %vid:vr = PseudoVID_V_M1 $noreg, -1, 5 /* e32 */, 3 /* ta, ma */
    ; CHECK-NEXT: %mask:vr = PseudoVMSLEU_VI_M1 %vid, 3, -1, 5 /* e32 */
    ; CHECK-NEXT: $v0 = COPY %mask
    ; CHECK-NEXT: %x:vr = PseudoVADD_VV_M1 $noreg, $v8, $v9, 4, 5 /* e32 */, 3 /* ta, ma */
    %vid:vr = PseudoVID_V_M1 $noreg, -1, 5, 3
    %mask:vr = PseudoVMSLEU_VI_M1 %vid, 3, -1, 5
    $v0 = COPY %mask
    %x:vrnov0 = PseudoVADD_VV_M1_MASK $noreg, $v8, $v9, $v0, -1, 5, 3
...
---
name: vmsltu_vx
body: |
  bb.0:
    liveins: $x1, $v8, $v9
    ; CHECK-LABEL: name: vmsltu_vx
    ; CHECK: liveins: $x1, $v8, $v9
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %avl:gprnox0 = COPY $x1
    ; CHECK-NEXT: %vid:vr = PseudoVID_V_M1 $noreg, -1, 5 /* e32 */, 3 /* ta, ma */
    ; CHECK-NEXT: %mask:vr = PseudoVMSLTU_VX_M1 %vid, %avl, -1, 5 /* e32 */
    ; CHECK-NEXT: $v0 = COPY %mask
    ; CHECK-NEXT: %x:vr = PseudoVADD_VV_M1 $noreg, $v8, $v9, %avl, 5 /* e32 */, 3 /* ta, ma */
    %avl:gpr = COPY $x1
    %vid:vr = PseudoVID_V_M1 $noreg, -1, 5, 3
    %mask:vr = PseudoVMSLTU_VX_M1 %vid, %avl, -1, 5
    $v0 = COPY %mask
    %x:vrnov0 = PseudoVADD_VV_M1_MASK $noreg, $v8, $v9, $v0, -1, 5, 3
...
---
name: non_vlmax
body: |
  bb.0:
    liveins: $v8, $v9
    ; CHECK-LABEL: name: non_vlmax
    ; CHECK: liveins: $v8, $v9
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %vid:vr = PseudoVID_V_M1 $noreg, -1, 5 /* e32 */, 3 /* ta, ma */
    ; CHECK-NEXT: %mask:vr = PseudoVMSLEU_VI_M1 %vid, 3, -1, 5 /* e32 */
    ; CHECK-NEXT: $v0 = COPY %mask
    ; CHECK-NEXT: %x:vrnov0 = PseudoVADD_VV_M1_MASK $noreg, $v8, $v9, $v0, 2, 5 /* e32 */, 3 /* ta, ma */
    %vid:vr = PseudoVID_V_M1 $noreg, -1, 5, 3
    %mask:vr = PseudoVMSLEU_VI_M1 %vid, 3, -1, 5
    $v0 = COPY %mask
    %x:vrnov0 = PseudoVADD_VV_M1_MASK $noreg, $v8, $v9, $v0, 2, 5, 3
...
---
name: vid_with_passthru
body: |
  bb.0:
    liveins: $v8, $v9, $v10
    ; CHECK-LABEL: name: vid_with_passthru
    ; CHECK: liveins: $v8, $v9, $v10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %vid:vr = PseudoVID_V_M1 $v10, -1, 5 /* e32 */, 3 /* ta, ma */
    ; CHECK-NEXT: %mask:vr = PseudoVMSLEU_VI_M1 %vid, 3, -1, 5 /* e32 */
    ; CHECK-NEXT: $v0 = COPY %mask
    ; CHECK-NEXT: %x:vr = PseudoVADD_VV_M1 $noreg, $v8, $v9, 4, 5 /* e32 */, 3 /* ta, ma */
    %vid:vr = PseudoVID_V_M1 $v10, -1, 5, 3
    %mask:vr = PseudoVMSLEU_VI_M1 %vid, 3, -1, 5
    $v0 = COPY %mask
    %x:vrnov0 = PseudoVADD_VV_M1_MASK $noreg, $v8, $v9, $v0, -1, 5, 3
...
---
name: vid_with_passthru_non_vlmax
body: |
  bb.0:
    liveins: $v8, $v9, $v10
    ; CHECK-LABEL: name: vid_with_passthru_non_vlmax
    ; CHECK: liveins: $v8, $v9, $v10
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: %vid:vr = PseudoVID_V_M1 $v10, 3, 5 /* e32 */, 3 /* ta, ma */
    ; CHECK-NEXT: %mask:vr = PseudoVMSLEU_VI_M1 %vid, 3, -1, 5 /* e32 */
    ; CHECK-NEXT: $v0 = COPY %mask
    ; CHECK-NEXT: %x:vrnov0 = PseudoVADD_VV_M1_MASK $noreg, $v8, $v9, $v0, -1, 5 /* e32 */, 3 /* ta, ma */
    %vid:vr = PseudoVID_V_M1 $v10, 3, 5, 3
    %mask:vr = PseudoVMSLEU_VI_M1 %vid, 3, -1, 5
    $v0 = COPY %mask
    %x:vrnov0 = PseudoVADD_VV_M1_MASK $noreg, $v8, $v9, $v0, -1, 5, 3
...
