; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple riscv64 -mattr=+v | FileCheck %s

define void @hoist_const_splats(ptr %p, i32 zeroext %n) {
; CHECK-LABEL: hoist_const_splats:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli a2, zero, e32, m2, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 1
; CHECK-NEXT:    li a2, 0
; CHECK-NEXT:  .LBB0_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    vsetvli a3, a1, e8, mf2, ta, ma
; CHECK-NEXT:    slli a4, a2, 2
; CHECK-NEXT:    add a4, a0, a4
; CHECK-NEXT:    sub a1, a1, a3
; CHECK-NEXT:    addw a2, a2, a3
; CHECK-NEXT:    vse32.v v8, (a4)
; CHECK-NEXT:    bnez a1, .LBB0_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    ret
entry:
  %n.zext = zext i32 %n to i64
  br label %loop

loop:
  %iv = phi i32 [0, %entry], [%iv.next, %loop]
  %avl = phi i64 [%n.zext, %entry], [%avl.next, %loop]
  %evl = call i32 @llvm.experimental.get.vector.length(i64 %avl, i32 4, i1 true)
  %gep = getelementptr i32, ptr %p, i32 %iv
  call void @llvm.vp.store(<vscale x 4 x i32> splat (i32 1), ptr %gep, <vscale x 4 x i1> splat (i1 true), i32 %evl)
  %iv.next = add i32 %iv, %evl
  %evl.zext = zext i32 %evl to i64
  %avl.next = sub i64 %avl, %evl.zext
  %ec = icmp eq i64
  %avl.next, 0
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}
